# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clients.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HRM_Clients_view(object):
    def setupUi(self, HRM_Clients_view):
        HRM_Clients_view.setObjectName("HRM_Clients_view")
        HRM_Clients_view.resize(1443, 735)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HRM_Clients_view.setWindowIcon(icon)
        HRM_Clients_view.setStyleSheet("background-color:rgb(40, 93, 117);")
        self.centralwidget = QtWidgets.QWidget(HRM_Clients_view)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 1351, 611))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget_record = QtWidgets.QTabWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.tabWidget_record.setFont(font)
        self.tabWidget_record.setStyleSheet("")
        self.tabWidget_record.setObjectName("tabWidget_record")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 1321, 541))
        self.groupBox_5.setStyleSheet("color:rgb(71, 214, 216)")
        self.groupBox_5.setObjectName("groupBox_5")
        self.line_3 = QtWidgets.QFrame(self.groupBox_5)
        self.line_3.setGeometry(QtCore.QRect(0, 40, 1311, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lcdNumber_user_id = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_user_id.setGeometry(QtCore.QRect(200, 10, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_user_id.sizePolicy().hasHeightForWidth())
        self.lcdNumber_user_id.setSizePolicy(sizePolicy)
        self.lcdNumber_user_id.setMinimumSize(QtCore.QSize(31, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_user_id.setFont(font)
        self.lcdNumber_user_id.setObjectName("lcdNumber_user_id")
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(16, 70, 791, 466))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.line = QtWidgets.QFrame(self.layoutWidget_5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_42.addWidget(self.line)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_35.addWidget(self.label_58)
        self.horizontalLayout_43.addLayout(self.verticalLayout_35)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem)
        self.verticalLayout_34.addLayout(self.horizontalLayout_43)
        self.lineEdit_IDNo_new = QtWidgets.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_IDNo_new.setFont(font)
        self.lineEdit_IDNo_new.setToolTip("")
        self.lineEdit_IDNo_new.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_IDNo_new.setObjectName("lineEdit_IDNo_new")
        self.verticalLayout_34.addWidget(self.lineEdit_IDNo_new)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_36.addWidget(self.label_59)
        self.horizontalLayout_44.addLayout(self.verticalLayout_36)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_44.addItem(spacerItem1)
        self.verticalLayout_34.addLayout(self.horizontalLayout_44)
        self.lineEdit_invoice_new = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_invoice_new.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_invoice_new.setFont(font)
        self.lineEdit_invoice_new.setToolTip("")
        self.lineEdit_invoice_new.setObjectName("lineEdit_invoice_new")
        self.verticalLayout_34.addWidget(self.lineEdit_invoice_new)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_45.addWidget(self.label_60)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem2)
        self.verticalLayout_34.addLayout(self.horizontalLayout_45)
        self.dateTimeEdit_stampNew = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.dateTimeEdit_stampNew.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit_stampNew.setFont(font)
        self.dateTimeEdit_stampNew.setObjectName("dateTimeEdit_stampNew")
        self.verticalLayout_34.addWidget(self.dateTimeEdit_stampNew)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_37.addWidget(self.label_61)
        self.horizontalLayout_46.addLayout(self.verticalLayout_37)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem3)
        self.verticalLayout_34.addLayout(self.horizontalLayout_46)
        self.lineEdit_kra_pin_new = QtWidgets.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_kra_pin_new.setFont(font)
        self.lineEdit_kra_pin_new.setToolTip("")
        self.lineEdit_kra_pin_new.setObjectName("lineEdit_kra_pin_new")
        self.verticalLayout_34.addWidget(self.lineEdit_kra_pin_new)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_38.addWidget(self.label_62)
        self.horizontalLayout_47.addLayout(self.verticalLayout_38)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem4)
        self.verticalLayout_34.addLayout(self.horizontalLayout_47)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.lineEdit_regNo_new = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_regNo_new.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_regNo_new.setFont(font)
        self.lineEdit_regNo_new.setObjectName("lineEdit_regNo_new")
        self.verticalLayout_33.addWidget(self.lineEdit_regNo_new)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_2.addWidget(self.label_49)
        self.textEdit_address_new = QtWidgets.QTextEdit(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_address_new.sizePolicy().hasHeightForWidth())
        self.textEdit_address_new.setSizePolicy(sizePolicy)
        self.textEdit_address_new.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_address_new.setFont(font)
        self.textEdit_address_new.setObjectName("textEdit_address_new")
        self.verticalLayout_2.addWidget(self.textEdit_address_new)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_33.addLayout(self.verticalLayout_2)
        self.horizontalLayout_42.addLayout(self.verticalLayout_33)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget_5)
        self.groupBox_6.setMinimumSize(QtCore.QSize(421, 266))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setCheckable(True)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 20, 401, 242))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_49.addWidget(self.label_4)
        self.verticalLayout_41.addLayout(self.horizontalLayout_49)
        self.lineEdit_org_name_new = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_org_name_new.setFont(font)
        self.lineEdit_org_name_new.setObjectName("lineEdit_org_name_new")
        self.verticalLayout_41.addWidget(self.lineEdit_org_name_new)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.verticalLayout_41.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_48.addLayout(self.verticalLayout_41)
        self.verticalLayout_40.addLayout(self.horizontalLayout_48)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_40.addWidget(self.label_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_51.addWidget(self.label_63)
        self.lineEdit_fn_repnew = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_fn_repnew.setFont(font)
        self.lineEdit_fn_repnew.setObjectName("lineEdit_fn_repnew")
        self.horizontalLayout_51.addWidget(self.lineEdit_fn_repnew)
        self.verticalLayout_42.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_52.addWidget(self.label_64)
        self.lineEdit_mn_repnew = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mn_repnew.setFont(font)
        self.lineEdit_mn_repnew.setObjectName("lineEdit_mn_repnew")
        self.horizontalLayout_52.addWidget(self.lineEdit_mn_repnew)
        self.verticalLayout_42.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_53.addWidget(self.label_65)
        self.lineEdit_ln_repnew = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ln_repnew.setFont(font)
        self.lineEdit_ln_repnew.setObjectName("lineEdit_ln_repnew")
        self.horizontalLayout_53.addWidget(self.lineEdit_ln_repnew)
        self.verticalLayout_42.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_30.addWidget(self.label_45)
        self.lineEdit_tell_repnew = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tell_repnew.setFont(font)
        self.lineEdit_tell_repnew.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_tell_repnew.setObjectName("lineEdit_tell_repnew")
        self.horizontalLayout_30.addWidget(self.lineEdit_tell_repnew)
        self.verticalLayout_42.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_31.addWidget(self.label_46)
        self.lineEdit_email_repnew = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_email_repnew.setFont(font)
        self.lineEdit_email_repnew.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_email_repnew.setObjectName("lineEdit_email_repnew")
        self.horizontalLayout_31.addWidget(self.lineEdit_email_repnew)
        self.verticalLayout_42.addLayout(self.horizontalLayout_31)
        self.verticalLayout_11.addLayout(self.verticalLayout_42)
        self.verticalLayout_40.addLayout(self.verticalLayout_11)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem6)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.horizontalLayout_42.addLayout(self.verticalLayout_10)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_42.addLayout(self.verticalLayout_39)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(810, 70, 501, 461))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.spinBox_workforce = QtWidgets.QSpinBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_workforce.setFont(font)
        self.spinBox_workforce.setMinimum(1)
        self.spinBox_workforce.setMaximum(600)
        self.spinBox_workforce.setObjectName("spinBox_workforce")
        self.horizontalLayout_4.addWidget(self.spinBox_workforce)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_skill_new = QtWidgets.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_skill_new.setFont(font)
        self.comboBox_skill_new.setObjectName("comboBox_skill_new")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.comboBox_skill_new.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_skill_new)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.comboBox_payrate_new = QtWidgets.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_payrate_new.setFont(font)
        self.comboBox_payrate_new.setObjectName("comboBox_payrate_new")
        self.comboBox_payrate_new.addItem("")
        self.comboBox_payrate_new.addItem("")
        self.comboBox_payrate_new.addItem("")
        self.comboBox_payrate_new.addItem("")
        self.comboBox_payrate_new.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_payrate_new)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.tableView_workers = QtWidgets.QTableView(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tableView_workers.setFont(font)
        self.tableView_workers.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.tableView_workers.setAlternatingRowColors(True)
        self.tableView_workers.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableView_workers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_workers.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView_workers.setSortingEnabled(False)
        self.tableView_workers.setObjectName("tableView_workers")
        self.verticalLayout_3.addWidget(self.tableView_workers)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.layoutWidget_5.raise_()
        self.layoutWidget_2.raise_()
        self.line_3.raise_()
        self.lcdNumber_user_id.raise_()
        self.tabWidget_record.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 1321, 531))
        self.groupBox_3.setStyleSheet("color:rgb(71, 214, 216)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(-90, 50, 1381, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.comboBox_clients_list = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_clients_list.setGeometry(QtCore.QRect(500, 20, 341, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_clients_list.setFont(font)
        self.comboBox_clients_list.setAcceptDrops(False)
        self.comboBox_clients_list.setObjectName("comboBox_clients_list")
        self.label_50 = QtWidgets.QLabel(self.groupBox_3)
        self.label_50.setGeometry(QtCore.QRect(383, 20, 101, 31))
        self.label_50.setObjectName("label_50")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 70, 771, 441))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.line_4 = QtWidgets.QFrame(self.layoutWidget_7)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_60.addWidget(self.line_4)
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_47.addWidget(self.label_71)
        self.lineEdit_IDNo_old = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_IDNo_old.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_IDNo_old.setFont(font)
        self.lineEdit_IDNo_old.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_IDNo_old.setObjectName("lineEdit_IDNo_old")
        self.verticalLayout_47.addWidget(self.lineEdit_IDNo_old)
        self.horizontalLayout_61.addLayout(self.verticalLayout_47)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem9)
        self.verticalLayout_46.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_72 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_48.addWidget(self.label_72)
        self.horizontalLayout_62.addLayout(self.verticalLayout_48)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_62.addItem(spacerItem10)
        self.verticalLayout_46.addLayout(self.horizontalLayout_62)
        self.lineEdit_invoice_old = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_invoice_old.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_invoice_old.setFont(font)
        self.lineEdit_invoice_old.setObjectName("lineEdit_invoice_old")
        self.verticalLayout_46.addWidget(self.lineEdit_invoice_old)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_73 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_63.addWidget(self.label_73)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem11)
        self.verticalLayout_46.addLayout(self.horizontalLayout_63)
        self.dateTimeEdit_stampOld = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.dateTimeEdit_stampOld.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit_stampOld.setFont(font)
        self.dateTimeEdit_stampOld.setObjectName("dateTimeEdit_stampOld")
        self.verticalLayout_46.addWidget(self.dateTimeEdit_stampOld)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_49.addWidget(self.label_74)
        self.lineEdit_kra_pin_old = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_kra_pin_old.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_kra_pin_old.setFont(font)
        self.lineEdit_kra_pin_old.setObjectName("lineEdit_kra_pin_old")
        self.verticalLayout_49.addWidget(self.lineEdit_kra_pin_old)
        self.horizontalLayout_64.addLayout(self.verticalLayout_49)
        self.verticalLayout_46.addLayout(self.horizontalLayout_64)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.label_75 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_50.addWidget(self.label_75)
        self.lineEdit_regNo_old = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_regNo_old.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_regNo_old.setFont(font)
        self.lineEdit_regNo_old.setObjectName("lineEdit_regNo_old")
        self.verticalLayout_50.addWidget(self.lineEdit_regNo_old)
        self.horizontalLayout_65.addLayout(self.verticalLayout_50)
        self.verticalLayout_46.addLayout(self.horizontalLayout_65)
        self.verticalLayout_45.addLayout(self.verticalLayout_46)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_7.addWidget(self.label_53)
        self.textEdit_address_old = QtWidgets.QTextEdit(self.layoutWidget_7)
        self.textEdit_address_old.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_address_old.sizePolicy().hasHeightForWidth())
        self.textEdit_address_old.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_address_old.setFont(font)
        self.textEdit_address_old.setStyleSheet("")
        self.textEdit_address_old.setObjectName("textEdit_address_old")
        self.verticalLayout_7.addWidget(self.textEdit_address_old)
        self.verticalLayout_45.addLayout(self.verticalLayout_7)
        self.horizontalLayout_60.addLayout(self.verticalLayout_45)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_8 = QtWidgets.QGroupBox(self.layoutWidget_7)
        self.groupBox_8.setMinimumSize(QtCore.QSize(421, 251))
        self.groupBox_8.setCheckable(True)
        self.groupBox_8.setChecked(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 20, 391, 221))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_67.addWidget(self.label_9)
        self.lineEdit_org_name_old = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_org_name_old.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_org_name_old.setFont(font)
        self.lineEdit_org_name_old.setObjectName("lineEdit_org_name_old")
        self.horizontalLayout_67.addWidget(self.lineEdit_org_name_old)
        self.verticalLayout_53.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.verticalLayout_53.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_66.addLayout(self.verticalLayout_53)
        self.verticalLayout_52.addLayout(self.horizontalLayout_66)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_52.addWidget(self.label_10)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_76 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_69.addWidget(self.label_76)
        self.lineEdit_fn_repold = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_fn_repold.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_fn_repold.setFont(font)
        self.lineEdit_fn_repold.setObjectName("lineEdit_fn_repold")
        self.horizontalLayout_69.addWidget(self.lineEdit_fn_repold)
        self.verticalLayout_54.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_77 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_70.addWidget(self.label_77)
        self.lineEdit_mn_repold = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_mn_repold.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mn_repold.setFont(font)
        self.lineEdit_mn_repold.setObjectName("lineEdit_mn_repold")
        self.horizontalLayout_70.addWidget(self.lineEdit_mn_repold)
        self.verticalLayout_54.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_78 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_71.addWidget(self.label_78)
        self.lineEdit_ln_repold = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_ln_repold.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ln_repold.setFont(font)
        self.lineEdit_ln_repold.setObjectName("lineEdit_ln_repold")
        self.horizontalLayout_71.addWidget(self.lineEdit_ln_repold)
        self.verticalLayout_54.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_32.addWidget(self.label_47)
        self.lineEdit_tell_repold = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_tell_repold.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tell_repold.setFont(font)
        self.lineEdit_tell_repold.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_tell_repold.setObjectName("lineEdit_tell_repold")
        self.horizontalLayout_32.addWidget(self.lineEdit_tell_repold)
        self.verticalLayout_54.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_33.addWidget(self.label_48)
        self.lineEdit_email_repold = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_email_repold.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_email_repold.setFont(font)
        self.lineEdit_email_repold.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_email_repold.setObjectName("lineEdit_email_repold")
        self.horizontalLayout_33.addWidget(self.lineEdit_email_repold)
        self.verticalLayout_54.addLayout(self.horizontalLayout_33)
        self.verticalLayout_52.addLayout(self.verticalLayout_54)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem12)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.horizontalLayout_60.addLayout(self.verticalLayout)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.horizontalLayout_60.addLayout(self.verticalLayout_51)
        self.layoutWidget_12 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_12.setGeometry(QtCore.QRect(790, 70, 511, 441))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.spinBox_workforce_2 = QtWidgets.QSpinBox(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_workforce_2.setFont(font)
        self.spinBox_workforce_2.setMinimum(1)
        self.spinBox_workforce_2.setMaximum(600)
        self.spinBox_workforce_2.setObjectName("spinBox_workforce_2")
        self.horizontalLayout_9.addWidget(self.spinBox_workforce_2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.comboBox_skill_new_2 = QtWidgets.QComboBox(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_skill_new_2.setFont(font)
        self.comboBox_skill_new_2.setObjectName("comboBox_skill_new_2")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.comboBox_skill_new_2.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_skill_new_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.comboBox_payrate_new_2 = QtWidgets.QComboBox(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_payrate_new_2.setFont(font)
        self.comboBox_payrate_new_2.setObjectName("comboBox_payrate_new_2")
        self.comboBox_payrate_new_2.addItem("")
        self.comboBox_payrate_new_2.addItem("")
        self.comboBox_payrate_new_2.addItem("")
        self.comboBox_payrate_new_2.addItem("")
        self.comboBox_payrate_new_2.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_payrate_new_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.tableView_workers_old = QtWidgets.QTableView(self.layoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tableView_workers_old.setFont(font)
        self.tableView_workers_old.setAlternatingRowColors(True)
        self.tableView_workers_old.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableView_workers_old.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_workers_old.setObjectName("tableView_workers_old")
        self.verticalLayout_21.addWidget(self.tableView_workers_old)
        self.verticalLayout_18.addLayout(self.verticalLayout_21)
        self.verticalLayout_8.addLayout(self.verticalLayout_18)
        self.tabWidget_record.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 1271, 521))
        self.groupBox_4.setStyleSheet("color:rgb(71, 214, 216)")
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget_records = QtWidgets.QTableView(self.groupBox_4)
        self.tableWidget_records.setGeometry(QtCore.QRect(10, 20, 1241, 491))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_records.setFont(font)
        self.tableWidget_records.setAlternatingRowColors(True)
        self.tableWidget_records.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_records.setObjectName("tableWidget_records")
        self.toolButton = QtWidgets.QToolButton(self.tab_4)
        self.toolButton.setGeometry(QtCore.QRect(1250, 0, 31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/icons8-process-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.tabWidget_record.addTab(self.tab_4, "")
        self.verticalLayout_9.addWidget(self.tabWidget_record)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem15)
        self.pushButton_reg = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setStyleSheet("color:rgb(85, 255, 255)")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.horizontalLayout_23.addWidget(self.pushButton_reg)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem16)
        self.pushButton_update = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.pushButton_update.setFont(font)
        self.pushButton_update.setStyleSheet("color:rgb(85, 255, 255)")
        self.pushButton_update.setObjectName("pushButton_update")
        self.horizontalLayout_23.addWidget(self.pushButton_update)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("color:rgb(85, 255, 255)")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_23.addWidget(self.pushButton_delete)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_23.addWidget(self.line_5)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.pushButton_login = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("color:rgb(85, 255, 255)")
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout_23.addWidget(self.pushButton_login)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem19)
        self.pushButton_back = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("color:rgb(85, 255, 255)")
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_23.addWidget(self.pushButton_back)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem20)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, 10, 1429, 51))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(35)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgb(40, 93, 117);color:rgb(71, 214, 216)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        HRM_Clients_view.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HRM_Clients_view)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1443, 21))
        self.menubar.setObjectName("menubar")
        HRM_Clients_view.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HRM_Clients_view)
        self.statusbar.setObjectName("statusbar")
        HRM_Clients_view.setStatusBar(self.statusbar)
        self.label_58.setBuddy(self.lineEdit_IDNo_new)
        self.label_59.setBuddy(self.lineEdit_invoice_new)
        self.label_61.setBuddy(self.lineEdit_kra_pin_new)
        self.label_62.setBuddy(self.lineEdit_regNo_new)
        self.label_49.setBuddy(self.textEdit_address_new)
        self.label_4.setBuddy(self.lineEdit_org_name_new)
        self.label_63.setBuddy(self.lineEdit_fn_repnew)
        self.label_64.setBuddy(self.lineEdit_mn_repnew)
        self.label_65.setBuddy(self.lineEdit_ln_repnew)
        self.label_45.setBuddy(self.lineEdit_tell_repnew)
        self.label_46.setBuddy(self.lineEdit_email_repnew)
        self.label_6.setBuddy(self.comboBox_skill_new)
        self.label_7.setBuddy(self.comboBox_payrate_new)
        self.label_50.setBuddy(self.comboBox_clients_list)
        self.label_71.setBuddy(self.lineEdit_IDNo_old)
        self.label_72.setBuddy(self.lineEdit_invoice_new)
        self.label_74.setBuddy(self.lineEdit_kra_pin_new)
        self.label_75.setBuddy(self.lineEdit_regNo_new)
        self.label_53.setBuddy(self.textEdit_address_old)
        self.label_9.setBuddy(self.lineEdit_org_name_new)
        self.label_76.setBuddy(self.lineEdit_fn_repold)
        self.label_77.setBuddy(self.lineEdit_mn_repold)
        self.label_78.setBuddy(self.lineEdit_ln_repold)
        self.label_47.setBuddy(self.lineEdit_tell_repnew)
        self.label_48.setBuddy(self.lineEdit_email_repnew)
        self.label_13.setBuddy(self.comboBox_skill_new)
        self.label_14.setBuddy(self.comboBox_payrate_new)

        self.retranslateUi(HRM_Clients_view)
        self.tabWidget_record.setCurrentIndex(0)
        self.tabWidget_record.currentChanged['int'].connect(self.tableWidget_records.update)
        QtCore.QMetaObject.connectSlotsByName(HRM_Clients_view)
        HRM_Clients_view.setTabOrder(self.pushButton_reg, self.lineEdit_invoice_new)
        HRM_Clients_view.setTabOrder(self.lineEdit_invoice_new, self.lineEdit_kra_pin_new)
        HRM_Clients_view.setTabOrder(self.lineEdit_kra_pin_new, self.lineEdit_regNo_new)
        HRM_Clients_view.setTabOrder(self.lineEdit_regNo_new, self.textEdit_address_new)
        HRM_Clients_view.setTabOrder(self.textEdit_address_new, self.groupBox_6)
        HRM_Clients_view.setTabOrder(self.groupBox_6, self.lineEdit_fn_repnew)
        HRM_Clients_view.setTabOrder(self.lineEdit_fn_repnew, self.lineEdit_mn_repnew)
        HRM_Clients_view.setTabOrder(self.lineEdit_mn_repnew, self.lineEdit_ln_repnew)
        HRM_Clients_view.setTabOrder(self.lineEdit_ln_repnew, self.lineEdit_tell_repnew)
        HRM_Clients_view.setTabOrder(self.lineEdit_tell_repnew, self.lineEdit_email_repnew)
        HRM_Clients_view.setTabOrder(self.lineEdit_email_repnew, self.spinBox_workforce)
        HRM_Clients_view.setTabOrder(self.spinBox_workforce, self.comboBox_skill_new)
        HRM_Clients_view.setTabOrder(self.comboBox_skill_new, self.comboBox_payrate_new)
        HRM_Clients_view.setTabOrder(self.comboBox_payrate_new, self.tableView_workers)
        HRM_Clients_view.setTabOrder(self.tableView_workers, self.comboBox_clients_list)
        HRM_Clients_view.setTabOrder(self.comboBox_clients_list, self.lineEdit_IDNo_old)
        HRM_Clients_view.setTabOrder(self.lineEdit_IDNo_old, self.lineEdit_invoice_old)
        HRM_Clients_view.setTabOrder(self.lineEdit_invoice_old, self.lineEdit_kra_pin_old)
        HRM_Clients_view.setTabOrder(self.lineEdit_kra_pin_old, self.lineEdit_regNo_old)
        HRM_Clients_view.setTabOrder(self.lineEdit_regNo_old, self.textEdit_address_old)
        HRM_Clients_view.setTabOrder(self.textEdit_address_old, self.groupBox_8)
        HRM_Clients_view.setTabOrder(self.groupBox_8, self.lineEdit_org_name_old)
        HRM_Clients_view.setTabOrder(self.lineEdit_org_name_old, self.lineEdit_fn_repold)
        HRM_Clients_view.setTabOrder(self.lineEdit_fn_repold, self.lineEdit_mn_repold)
        HRM_Clients_view.setTabOrder(self.lineEdit_mn_repold, self.lineEdit_ln_repold)
        HRM_Clients_view.setTabOrder(self.lineEdit_ln_repold, self.lineEdit_tell_repold)
        HRM_Clients_view.setTabOrder(self.lineEdit_tell_repold, self.lineEdit_email_repold)
        HRM_Clients_view.setTabOrder(self.lineEdit_email_repold, self.spinBox_workforce_2)
        HRM_Clients_view.setTabOrder(self.spinBox_workforce_2, self.comboBox_skill_new_2)
        HRM_Clients_view.setTabOrder(self.comboBox_skill_new_2, self.comboBox_payrate_new_2)
        HRM_Clients_view.setTabOrder(self.comboBox_payrate_new_2, self.tableView_workers_old)
        HRM_Clients_view.setTabOrder(self.tableView_workers_old, self.tableWidget_records)
        HRM_Clients_view.setTabOrder(self.tableWidget_records, self.lineEdit_IDNo_new)
        HRM_Clients_view.setTabOrder(self.lineEdit_IDNo_new, self.pushButton_update)
        HRM_Clients_view.setTabOrder(self.pushButton_update, self.pushButton_delete)
        HRM_Clients_view.setTabOrder(self.pushButton_delete, self.pushButton_login)
        HRM_Clients_view.setTabOrder(self.pushButton_login, self.pushButton_back)
        HRM_Clients_view.setTabOrder(self.pushButton_back, self.dateTimeEdit_stampOld)
        HRM_Clients_view.setTabOrder(self.dateTimeEdit_stampOld, self.dateTimeEdit_stampNew)
        HRM_Clients_view.setTabOrder(self.dateTimeEdit_stampNew, self.tabWidget_record)

    def retranslateUi(self, HRM_Clients_view):
        _translate = QtCore.QCoreApplication.translate
        HRM_Clients_view.setWindowTitle(_translate("HRM_Clients_view", "Client Window"))
        self.groupBox_5.setTitle(_translate("HRM_Clients_view", "Enter New Client  Details"))
        self.label_58.setText(_translate("HRM_Clients_view", "National ID No./ Company Reg No."))
        self.lineEdit_IDNo_new.setStatusTip(_translate("HRM_Clients_view", "Your National Idetification Document Number"))
        self.label_59.setText(_translate("HRM_Clients_view", "Client Invoice No. :"))
        self.lineEdit_invoice_new.setStatusTip(_translate("HRM_Clients_view", "Client Auto Invoice Number"))
        self.label_60.setText(_translate("HRM_Clients_view", "Registration Date Stamp"))
        self.label_61.setText(_translate("HRM_Clients_view", "KRA PIN"))
        self.lineEdit_kra_pin_new.setStatusTip(_translate("HRM_Clients_view", "Kenya Revenue of Authority Personal Identification Number"))
        self.label_62.setText(_translate("HRM_Clients_view", "Registration Number:"))
        self.lineEdit_regNo_new.setStatusTip(_translate("HRM_Clients_view", "HRM User Registration number"))
        self.label_49.setText(_translate("HRM_Clients_view", "Address :"))
        self.textEdit_address_new.setStatusTip(_translate("HRM_Clients_view", "User Physical Address "))
        self.groupBox_6.setTitle(_translate("HRM_Clients_view", "Organization/Company Client"))
        self.label_4.setText(_translate("HRM_Clients_view", "Company/Organization Name :"))
        self.lineEdit_org_name_new.setStatusTip(_translate("HRM_Clients_view", "Clients Organization Name"))
        self.label_5.setText(_translate("HRM_Clients_view", "Representative Names :"))
        self.label_63.setText(_translate("HRM_Clients_view", "First Name :"))
        self.lineEdit_fn_repnew.setStatusTip(_translate("HRM_Clients_view", "Company Representative First Name"))
        self.label_64.setText(_translate("HRM_Clients_view", "Middle Name :"))
        self.lineEdit_mn_repnew.setStatusTip(_translate("HRM_Clients_view", "Company Representative Middle Name"))
        self.label_65.setText(_translate("HRM_Clients_view", "Last Name :"))
        self.lineEdit_ln_repnew.setStatusTip(_translate("HRM_Clients_view", "Company Representative Last Name"))
        self.label_45.setText(_translate("HRM_Clients_view", "Phone Number :"))
        self.lineEdit_tell_repnew.setStatusTip(_translate("HRM_Clients_view", "Company Representative Phone Number"))
        self.label_46.setText(_translate("HRM_Clients_view", "Email :"))
        self.lineEdit_email_repnew.setStatusTip(_translate("HRM_Clients_view", "Company Representative Email Address"))
        self.label_8.setText(_translate("HRM_Clients_view", "Invoicing"))
        self.spinBox_workforce.setStatusTip(_translate("HRM_Clients_view", "Number of wokers needed"))
        self.label_3.setText(_translate("HRM_Clients_view", "Number of Workers I Require :"))
        self.label_6.setText(_translate("HRM_Clients_view", "Categories Available :"))
        self.comboBox_skill_new.setStatusTip(_translate("HRM_Clients_view", "Skill set Requirment"))
        self.comboBox_skill_new.setItemText(0, _translate("HRM_Clients_view", "choose a skill-set category..."))
        self.comboBox_skill_new.setItemText(1, _translate("HRM_Clients_view", "House Keeping"))
        self.comboBox_skill_new.setItemText(2, _translate("HRM_Clients_view", "Cathering Services"))
        self.comboBox_skill_new.setItemText(3, _translate("HRM_Clients_view", "Gaurd/Watch Personnel"))
        self.comboBox_skill_new.setItemText(4, _translate("HRM_Clients_view", "Property Security"))
        self.comboBox_skill_new.setItemText(5, _translate("HRM_Clients_view", "Personal Security"))
        self.comboBox_skill_new.setItemText(6, _translate("HRM_Clients_view", "Accountants"))
        self.comboBox_skill_new.setItemText(7, _translate("HRM_Clients_view", "Event Organizing Personnel"))
        self.comboBox_skill_new.setItemText(8, _translate("HRM_Clients_view", "Electric Retailers Personnel"))
        self.comboBox_skill_new.setItemText(9, _translate("HRM_Clients_view", "Hardware Retailers Personnel"))
        self.comboBox_skill_new.setItemText(10, _translate("HRM_Clients_view", "Pharmacutical Retailers Personnel"))
        self.comboBox_skill_new.setItemText(11, _translate("HRM_Clients_view", "Electronic Retailers Personnel"))
        self.comboBox_skill_new.setItemText(12, _translate("HRM_Clients_view", "Agro Retailers Personnel"))
        self.comboBox_skill_new.setItemText(13, _translate("HRM_Clients_view", "Automobile Retailers Personnel"))
        self.label_7.setText(_translate("HRM_Clients_view", "Rate of Payment :"))
        self.comboBox_payrate_new.setStatusTip(_translate("HRM_Clients_view", "Payment Rate requirement"))
        self.comboBox_payrate_new.setItemText(0, _translate("HRM_Clients_view", "choose a rate..."))
        self.comboBox_payrate_new.setItemText(1, _translate("HRM_Clients_view", "per Hour"))
        self.comboBox_payrate_new.setItemText(2, _translate("HRM_Clients_view", "per Day"))
        self.comboBox_payrate_new.setItemText(3, _translate("HRM_Clients_view", "per Week"))
        self.comboBox_payrate_new.setItemText(4, _translate("HRM_Clients_view", "per Month"))
        self.label_2.setText(_translate("HRM_Clients_view", "List of Available Workers"))
        self.tableView_workers.setStatusTip(_translate("HRM_Clients_view", "Worker  availability pick list. click to multi select workers"))
        self.tabWidget_record.setTabText(self.tabWidget_record.indexOf(self.tab), _translate("HRM_Clients_view", "New Clients"))
        self.groupBox_3.setTitle(_translate("HRM_Clients_view", "Enter Existing Client  Details"))
        self.comboBox_clients_list.setStatusTip(_translate("HRM_Clients_view", "Select client  from available list, if missing, plese click New Client tab to regester new"))
        self.label_50.setText(_translate("HRM_Clients_view", "Client Name :"))
        self.label_71.setText(_translate("HRM_Clients_view", "National ID No./Company Registration No."))
        self.lineEdit_IDNo_old.setStatusTip(_translate("HRM_Clients_view", "User-Auto filled National Identification Number or the Company Registration number"))
        self.label_72.setText(_translate("HRM_Clients_view", "Client Invoice No. :"))
        self.lineEdit_invoice_old.setStatusTip(_translate("HRM_Clients_view", "Auto-generated Client Invoice number"))
        self.label_73.setText(_translate("HRM_Clients_view", "Registration Date Stamp"))
        self.label_74.setText(_translate("HRM_Clients_view", "KRA PIN"))
        self.lineEdit_kra_pin_old.setStatusTip(_translate("HRM_Clients_view", "Kenya Revenue of Authority Personal Identification Number"))
        self.label_75.setText(_translate("HRM_Clients_view", "Registration Number:"))
        self.lineEdit_regNo_old.setStatusTip(_translate("HRM_Clients_view", "auto filled  HRM user registration number"))
        self.label_53.setText(_translate("HRM_Clients_view", "Address :"))
        self.textEdit_address_old.setStatusTip(_translate("HRM_Clients_view", "auto filled client physical address"))
        self.groupBox_8.setTitle(_translate("HRM_Clients_view", "Organization/Company Client"))
        self.label_9.setText(_translate("HRM_Clients_view", "Company/Organization Name :"))
        self.label_10.setText(_translate("HRM_Clients_view", "Representative Names :"))
        self.label_76.setText(_translate("HRM_Clients_view", "First Name :"))
        self.label_77.setText(_translate("HRM_Clients_view", "Middle Name :"))
        self.label_78.setText(_translate("HRM_Clients_view", "Last Name :"))
        self.label_47.setText(_translate("HRM_Clients_view", "Phone Number :"))
        self.label_48.setText(_translate("HRM_Clients_view", "Email :"))
        self.label_11.setText(_translate("HRM_Clients_view", "Invoicing"))
        self.spinBox_workforce_2.setStatusTip(_translate("HRM_Clients_view", "Number of wokers needed"))
        self.label_12.setText(_translate("HRM_Clients_view", "Number of Workers I Require :"))
        self.label_13.setText(_translate("HRM_Clients_view", "Categories Available :"))
        self.comboBox_skill_new_2.setStatusTip(_translate("HRM_Clients_view", "Skill set Requirment"))
        self.comboBox_skill_new_2.setItemText(0, _translate("HRM_Clients_view", "choose a skill-set category..."))
        self.comboBox_skill_new_2.setItemText(1, _translate("HRM_Clients_view", "House Keeping"))
        self.comboBox_skill_new_2.setItemText(2, _translate("HRM_Clients_view", "Cathering Services"))
        self.comboBox_skill_new_2.setItemText(3, _translate("HRM_Clients_view", "Gaurd/Watch Personnel"))
        self.comboBox_skill_new_2.setItemText(4, _translate("HRM_Clients_view", "Property Security"))
        self.comboBox_skill_new_2.setItemText(5, _translate("HRM_Clients_view", "Personal Security"))
        self.comboBox_skill_new_2.setItemText(6, _translate("HRM_Clients_view", "Accountants"))
        self.comboBox_skill_new_2.setItemText(7, _translate("HRM_Clients_view", "Event Organizing Personnel"))
        self.comboBox_skill_new_2.setItemText(8, _translate("HRM_Clients_view", "Electric Retailers Personnel"))
        self.comboBox_skill_new_2.setItemText(9, _translate("HRM_Clients_view", "Hardware Retailers Personnel"))
        self.comboBox_skill_new_2.setItemText(10, _translate("HRM_Clients_view", "Pharmacutical Retailers Personnel"))
        self.comboBox_skill_new_2.setItemText(11, _translate("HRM_Clients_view", "Electronic Retailers Personnel"))
        self.comboBox_skill_new_2.setItemText(12, _translate("HRM_Clients_view", "Agro Retailers Personnel"))
        self.comboBox_skill_new_2.setItemText(13, _translate("HRM_Clients_view", "Automobile Retailers Personnel"))
        self.label_14.setText(_translate("HRM_Clients_view", "Rate of Payment :"))
        self.comboBox_payrate_new_2.setStatusTip(_translate("HRM_Clients_view", "Payment Rate requirement"))
        self.comboBox_payrate_new_2.setItemText(0, _translate("HRM_Clients_view", "choose a rate..."))
        self.comboBox_payrate_new_2.setItemText(1, _translate("HRM_Clients_view", "per Hour"))
        self.comboBox_payrate_new_2.setItemText(2, _translate("HRM_Clients_view", "per Day"))
        self.comboBox_payrate_new_2.setItemText(3, _translate("HRM_Clients_view", "per Week"))
        self.comboBox_payrate_new_2.setItemText(4, _translate("HRM_Clients_view", "per Month"))
        self.label_15.setText(_translate("HRM_Clients_view", "List of Available Workers"))
        self.tabWidget_record.setTabText(self.tabWidget_record.indexOf(self.tab_3), _translate("HRM_Clients_view", "Existing Clients"))
        self.groupBox_4.setTitle(_translate("HRM_Clients_view", "Data view"))
        self.toolButton.setToolTip(_translate("HRM_Clients_view", "click to refresh the table"))
        self.toolButton.setStatusTip(_translate("HRM_Clients_view", "click Refresh table"))
        self.toolButton.setText(_translate("HRM_Clients_view", "Refresh"))
        self.tabWidget_record.setTabText(self.tabWidget_record.indexOf(self.tab_4), _translate("HRM_Clients_view", "Data View"))
        self.pushButton_reg.setText(_translate("HRM_Clients_view", "Register"))
        self.pushButton_update.setText(_translate("HRM_Clients_view", "Update"))
        self.pushButton_delete.setText(_translate("HRM_Clients_view", "Delete"))
        self.pushButton_login.setText(_translate("HRM_Clients_view", "Login"))
        self.pushButton_back.setText(_translate("HRM_Clients_view", "Back"))
        self.label.setText(_translate("HRM_Clients_view", "Human Resource Managment System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HRM_Clients_view = QtWidgets.QMainWindow()
    ui = Ui_HRM_Clients_view()
    ui.setupUi(HRM_Clients_view)
    HRM_Clients_view.show()
    sys.exit(app.exec_())

