# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HRM_Dashboard_view(object):
    def setupUi(self, HRM_Dashboard_view):
        HRM_Dashboard_view.setObjectName("HRM_Dashboard_view")
        HRM_Dashboard_view.resize(1399, 718)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HRM_Dashboard_view.setWindowIcon(icon)
        HRM_Dashboard_view.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.layoutWidget = QtWidgets.QWidget(HRM_Dashboard_view)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 1341, 597))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(48, 50))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../images/logo.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setFamily("Roman")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet(")")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setMinimumSize(QtCore.QSize(1150, 519))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(10)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../images/solar.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.splitter)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.layoutWidget2 = QtWidgets.QWidget(HRM_Dashboard_view)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 251, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_9 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_2.addWidget(self.line_9)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/services.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.toolButton_2 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/comments.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/maintenance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon3)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_2.addWidget(self.line_7)
        self.toolButton_4 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/male.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon4)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_2.addWidget(self.toolButton_4)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_2.addWidget(self.line_5)
        self.toolButton_5 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/bug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon5)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_2.addWidget(self.toolButton_5)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.toolButton_6 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_6.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon6)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_2.addWidget(self.toolButton_6)

        self.retranslateUi(HRM_Dashboard_view)
        QtCore.QMetaObject.connectSlotsByName(HRM_Dashboard_view)

    def retranslateUi(self, HRM_Dashboard_view):
        _translate = QtCore.QCoreApplication.translate
        HRM_Dashboard_view.setWindowTitle(_translate("HRM_Dashboard_view", "User Dashboard"))
        self.label.setText(_translate("HRM_Dashboard_view", "Human Resourse Management System"))
        self.pushButton.setToolTip(_translate("HRM_Dashboard_view", "<html><head/><body><p>User Login</p></body></html>"))
        self.pushButton.setText(_translate("HRM_Dashboard_view", "User Login"))
        self.pushButton_2.setText(_translate("HRM_Dashboard_view", "Register A New account"))
        self.pushButton_3.setText(_translate("HRM_Dashboard_view", "Demo"))
        self.pushButton_4.setText(_translate("HRM_Dashboard_view", "Website"))
        self.toolButton.setToolTip(_translate("HRM_Dashboard_view", "System Services"))
        self.toolButton.setStatusTip(_translate("HRM_Dashboard_view", "Services"))
        self.toolButton_2.setToolTip(_translate("HRM_Dashboard_view", "System Records"))
        self.toolButton_2.setStatusTip(_translate("HRM_Dashboard_view", "Meetings"))
        self.toolButton_3.setToolTip(_translate("HRM_Dashboard_view", "system Settings"))
        self.toolButton_3.setStatusTip(_translate("HRM_Dashboard_view", "System Settings"))
        self.toolButton_4.setToolTip(_translate("HRM_Dashboard_view", "system Users"))
        self.toolButton_4.setStatusTip(_translate("HRM_Dashboard_view", "System Users"))
        self.toolButton_5.setToolTip(_translate("HRM_Dashboard_view", "system Error correction"))
        self.toolButton_5.setStatusTip(_translate("HRM_Dashboard_view", "Error Debugging"))
        self.toolButton_6.setToolTip(_translate("HRM_Dashboard_view", "Need Help"))
        self.toolButton_6.setStatusTip(_translate("HRM_Dashboard_view", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HRM_Dashboard_view = QtWidgets.QDialog()
    ui = Ui_HRM_Dashboard_view()
    ui.setupUi(HRM_Dashboard_view)
    HRM_Dashboard_view.show()
    sys.exit(app.exec_())

