# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HRM_Employee_view(object):
    def setupUi(self, HRM_Employee_view):
        HRM_Employee_view.setObjectName("HRM_Employee_view")
        HRM_Employee_view.resize(1379, 926)
        HRM_Employee_view.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HRM_Employee_view.setWindowIcon(icon)
        HRM_Employee_view.setStyleSheet("background-color:rgb(40, 93, 117);")
        self.tabWidget = QtWidgets.QTabWidget(HRM_Employee_view)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 1311, 601))
        font = QtGui.QFont()
        font.setFamily("System")
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 1281, 541))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color:rgb(0, 255, 255)")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber_user_id = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_user_id.setGeometry(QtCore.QRect(80, 20, 161, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_user_id.sizePolicy().hasHeightForWidth())
        self.lcdNumber_user_id.setSizePolicy(sizePolicy)
        self.lcdNumber_user_id.setMinimumSize(QtCore.QSize(31, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_user_id.setFont(font)
        self.lcdNumber_user_id.setObjectName("lcdNumber_user_id")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 89, 1241, 445))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_28.addWidget(self.label_35)
        self.lineEdit_IDNo = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_IDNo.setFont(font)
        self.lineEdit_IDNo.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_IDNo.setObjectName("lineEdit_IDNo")
        self.verticalLayout_28.addWidget(self.lineEdit_IDNo)
        self.verticalLayout_11.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_11.addLayout(self.verticalLayout_29)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_9.addWidget(self.label_36)
        self.lineEdit_hrm_code = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_hrm_code.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_hrm_code.setFont(font)
        self.lineEdit_hrm_code.setObjectName("lineEdit_hrm_code")
        self.verticalLayout_9.addWidget(self.lineEdit_hrm_code)
        self.verticalLayout_30.addLayout(self.verticalLayout_9)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_30.addWidget(self.label_37)
        self.dateTime_stamp = QtWidgets.QLineEdit(self.layoutWidget)
        self.dateTime_stamp.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.dateTime_stamp.setFont(font)
        self.dateTime_stamp.setObjectName("dateTime_stamp")
        self.verticalLayout_30.addWidget(self.dateTime_stamp)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_31.addWidget(self.label_38)
        self.lineEdit_kra_pin = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_kra_pin.setFont(font)
        self.lineEdit_kra_pin.setInputMethodHints(QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_kra_pin.setMaxLength(32767)
        self.lineEdit_kra_pin.setObjectName("lineEdit_kra_pin")
        self.verticalLayout_31.addWidget(self.lineEdit_kra_pin)
        self.verticalLayout_30.addLayout(self.verticalLayout_31)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.lineEdit_regNo = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_regNo.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_regNo.setFont(font)
        self.lineEdit_regNo.setObjectName("lineEdit_regNo")
        self.verticalLayout_10.addWidget(self.lineEdit_regNo)
        self.verticalLayout_30.addLayout(self.verticalLayout_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_4.addWidget(self.label_39)
        self.textEdit_address = QtWidgets.QTextEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_address.setFont(font)
        self.textEdit_address.setObjectName("textEdit_address")
        self.verticalLayout_4.addWidget(self.textEdit_address)
        self.verticalLayout_30.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem)
        self.verticalLayout_11.addLayout(self.verticalLayout_30)
        self.horizontalLayout_34.addLayout(self.verticalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem1)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_32.addWidget(self.line_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_32.addLayout(self.horizontalLayout_15)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_6.addWidget(self.label_40)
        self.lineEdit_fn = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_fn.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_fn.setFont(font)
        self.lineEdit_fn.setObjectName("lineEdit_fn")
        self.horizontalLayout_6.addWidget(self.lineEdit_fn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_5.addWidget(self.label_41)
        self.lineEdit_mn = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_mn.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mn.setFont(font)
        self.lineEdit_mn.setObjectName("lineEdit_mn")
        self.horizontalLayout_5.addWidget(self.lineEdit_mn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_8.addWidget(self.label_42)
        self.lineEdit_ln = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ln.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ln.setFont(font)
        self.lineEdit_ln.setObjectName("lineEdit_ln")
        self.horizontalLayout_8.addWidget(self.lineEdit_ln)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_11.addWidget(self.label_43)
        self.lineEdit_tell = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tell.sizePolicy().hasHeightForWidth())
        self.lineEdit_tell.setSizePolicy(sizePolicy)
        self.lineEdit_tell.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tell.setFont(font)
        self.lineEdit_tell.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_tell.setObjectName("lineEdit_tell")
        self.horizontalLayout_11.addWidget(self.lineEdit_tell)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_10.addWidget(self.label_44)
        self.lineEdit_email = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_email.sizePolicy().hasHeightForWidth())
        self.lineEdit_email.setSizePolicy(sizePolicy)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_10.addWidget(self.lineEdit_email)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_33.addLayout(self.horizontalLayout_9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_4.addWidget(self.label_45)
        self.radioButton_m = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_m.setFont(font)
        self.radioButton_m.setObjectName("radioButton_m")
        self.horizontalLayout_4.addWidget(self.radioButton_m)
        self.radioButton_f = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_f.setFont(font)
        self.radioButton_f.setObjectName("radioButton_f")
        self.horizontalLayout_4.addWidget(self.radioButton_f)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_3.addWidget(self.label_46)
        self.dateEdit_dob = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_dob.setFont(font)
        self.dateEdit_dob.setMaximumDate(QtCore.QDate(2018, 9, 14))
        self.dateEdit_dob.setMinimumDate(QtCore.QDate(1920, 9, 14))
        self.dateEdit_dob.setCalendarPopup(True)
        self.dateEdit_dob.setObjectName("dateEdit_dob")
        self.horizontalLayout_3.addWidget(self.dateEdit_dob)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_33.addLayout(self.verticalLayout_7)
        self.verticalLayout_32.addLayout(self.verticalLayout_33)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_skill = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_skill.sizePolicy().hasHeightForWidth())
        self.comboBox_skill.setSizePolicy(sizePolicy)
        self.comboBox_skill.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_skill.setFont(font)
        self.comboBox_skill.setObjectName("comboBox_skill")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_skill)
        self.verticalLayout_32.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(170, 210))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 151, 185))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_day = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_day.setFont(font)
        self.radioButton_day.setObjectName("radioButton_day")
        self.verticalLayout.addWidget(self.radioButton_day)
        self.radioButton_hr = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_hr.setFont(font)
        self.radioButton_hr.setObjectName("radioButton_hr")
        self.verticalLayout.addWidget(self.radioButton_hr)
        self.radioButton_wk5 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_wk5.setFont(font)
        self.radioButton_wk5.setObjectName("radioButton_wk5")
        self.verticalLayout.addWidget(self.radioButton_wk5)
        self.radioButton_wk6 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_wk6.setFont(font)
        self.radioButton_wk6.setObjectName("radioButton_wk6")
        self.verticalLayout.addWidget(self.radioButton_wk6)
        self.radioButton_wk7 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_wk7.setFont(font)
        self.radioButton_wk7.setObjectName("radioButton_wk7")
        self.verticalLayout.addWidget(self.radioButton_wk7)
        self.radioButton_mth21 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_mth21.setFont(font)
        self.radioButton_mth21.setObjectName("radioButton_mth21")
        self.verticalLayout.addWidget(self.radioButton_mth21)
        self.radioButton_mth25 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_mth25.setFont(font)
        self.radioButton_mth25.setObjectName("radioButton_mth25")
        self.verticalLayout.addWidget(self.radioButton_mth25)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(160, 160))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 20, 131, 131))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 160, 160))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(160, 160))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 137, 131))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_imm = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_imm.setFont(font)
        self.radioButton_imm.setObjectName("radioButton_imm")
        self.verticalLayout_12.addWidget(self.radioButton_imm)
        self.radioButton_aday = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_aday.setFont(font)
        self.radioButton_aday.setObjectName("radioButton_aday")
        self.verticalLayout_12.addWidget(self.radioButton_aday)
        self.radioButton_2wks = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2wks.setFont(font)
        self.radioButton_2wks.setObjectName("radioButton_2wks")
        self.verticalLayout_12.addWidget(self.radioButton_2wks)
        self.radioButton_1wk = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_1wk.setFont(font)
        self.radioButton_1wk.setObjectName("radioButton_1wk")
        self.verticalLayout_12.addWidget(self.radioButton_1wk)
        self.radioButton_1mth = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_1mth.setFont(font)
        self.radioButton_1mth.setObjectName("radioButton_1mth")
        self.verticalLayout_12.addWidget(self.radioButton_1mth)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.spinBox_experience = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_experience.setObjectName("spinBox_experience")
        self.horizontalLayout_13.addWidget(self.spinBox_experience)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_32.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(270, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem3)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.verticalLayout_32.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_34.addLayout(self.verticalLayout_32)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(360, 20, 471, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.layoutWidget.raise_()
        self.label.raise_()
        self.lcdNumber_user_id.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_6)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1281, 502))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tableWidget_records = QtWidgets.QTableView(self.formLayoutWidget_2)
        self.tableWidget_records.setMinimumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_records.setFont(font)
        self.tableWidget_records.setAutoFillBackground(True)
        self.tableWidget_records.setStyleSheet("color:rgb(38, 152, 154) background-colorrgb(0, 255, 0);")
        self.tableWidget_records.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_records.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_records.setAlternatingRowColors(True)
        self.tableWidget_records.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_records.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_records.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_records.setSortingEnabled(True)
        self.tableWidget_records.setObjectName("tableWidget_records")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tableWidget_records)
        self.tabWidget.addTab(self.tab_6, "")
        self.layoutWidget1 = QtWidgets.QWidget(HRM_Employee_view)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 640, 1051, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem5)
        self.pushButton_reg = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.horizontalLayout_35.addWidget(self.pushButton_reg)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem7)
        self.pushButton_delete = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout_35.addWidget(self.pushButton_delete)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem8)
        self.pushButton_login = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout_35.addWidget(self.pushButton_login)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem9)
        self.pushButton_back = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("color:rgb(255, 255, 255)")
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_35.addWidget(self.pushButton_back)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem10)
        self.label_35.setBuddy(self.lineEdit_IDNo)
        self.label_36.setBuddy(self.lineEdit_hrm_code)
        self.label_38.setBuddy(self.lineEdit_kra_pin)
        self.label_18.setBuddy(self.lineEdit_regNo)
        self.label_39.setBuddy(self.textEdit_address)
        self.label_40.setBuddy(self.lineEdit_fn)
        self.label_41.setBuddy(self.lineEdit_mn)
        self.label_42.setBuddy(self.lineEdit_ln)
        self.label_43.setBuddy(self.lineEdit_tell)
        self.label_44.setBuddy(self.lineEdit_email)
        self.label_45.setBuddy(self.radioButton_f)
        self.label_46.setBuddy(self.dateEdit_dob)
        self.label_2.setBuddy(self.comboBox_skill)

        self.retranslateUi(HRM_Employee_view)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HRM_Employee_view)

    def retranslateUi(self, HRM_Employee_view):
        _translate = QtCore.QCoreApplication.translate
        HRM_Employee_view.setWindowTitle(_translate("HRM_Employee_view", "HRM Employee Registration Form"))
        self.groupBox_3.setTitle(_translate("HRM_Employee_view", "Enter New Employee  Details"))
        self.lcdNumber_user_id.setStatusTip(_translate("HRM_Employee_view", "Auto count the number of Employees in the system"))
        self.label_35.setText(_translate("HRM_Employee_view", "National ID No."))
        self.lineEdit_IDNo.setStatusTip(_translate("HRM_Employee_view", "Enter Employee National ID Number"))
        self.label_36.setText(_translate("HRM_Employee_view", "Employee HRM Code :"))
        self.lineEdit_hrm_code.setStatusTip(_translate("HRM_Employee_view", "Auto filled Employee system Code"))
        self.label_37.setText(_translate("HRM_Employee_view", "Registration Date Stamp"))
        self.dateTime_stamp.setStatusTip(_translate("HRM_Employee_view", "System set time stamp"))
        self.label_38.setText(_translate("HRM_Employee_view", "KRA PIN"))
        self.lineEdit_kra_pin.setStatusTip(_translate("HRM_Employee_view", "Enter Kenya Revenue of Authority Personal Identification Number"))
        self.label_18.setText(_translate("HRM_Employee_view", "Registration Number:"))
        self.lineEdit_regNo.setStatusTip(_translate("HRM_Employee_view", "Auto filled user registration number"))
        self.label_39.setText(_translate("HRM_Employee_view", "Address :"))
        self.textEdit_address.setStatusTip(_translate("HRM_Employee_view", "Enter Employee physical address"))
        self.label_40.setText(_translate("HRM_Employee_view", "First Name :"))
        self.lineEdit_fn.setStatusTip(_translate("HRM_Employee_view", "Enter Employee First Name"))
        self.label_41.setText(_translate("HRM_Employee_view", "Middle Name :"))
        self.lineEdit_mn.setStatusTip(_translate("HRM_Employee_view", "Enter Employee First Name"))
        self.label_42.setText(_translate("HRM_Employee_view", "Last Name :"))
        self.lineEdit_ln.setStatusTip(_translate("HRM_Employee_view", "Enter Employee First Name"))
        self.label_43.setText(_translate("HRM_Employee_view", "Phone Number :"))
        self.lineEdit_tell.setStatusTip(_translate("HRM_Employee_view", "Enter Employee Phone Number"))
        self.label_44.setText(_translate("HRM_Employee_view", "Email :"))
        self.lineEdit_email.setStatusTip(_translate("HRM_Employee_view", "Enter Employee Email address"))
        self.label_45.setStatusTip(_translate("HRM_Employee_view", "Select User Gender"))
        self.label_45.setText(_translate("HRM_Employee_view", "Gender"))
        self.radioButton_m.setText(_translate("HRM_Employee_view", "Male"))
        self.radioButton_f.setText(_translate("HRM_Employee_view", "Female"))
        self.label_46.setText(_translate("HRM_Employee_view", "Date Of Birth :"))
        self.dateEdit_dob.setStatusTip(_translate("HRM_Employee_view", "Select Employee date of Birth"))
        self.dateEdit_dob.setDisplayFormat(_translate("HRM_Employee_view", "d/M/yyyy"))
        self.label_2.setText(_translate("HRM_Employee_view", "Skill- Set Category"))
        self.comboBox_skill.setStatusTip(_translate("HRM_Employee_view", "Select worker skill set"))
        self.comboBox_skill.setItemText(0, _translate("HRM_Employee_view", "Select a Speciallity Category..."))
        self.comboBox_skill.setItemText(1, _translate("HRM_Employee_view", "House Keeping"))
        self.comboBox_skill.setItemText(2, _translate("HRM_Employee_view", "Personal/Property Security"))
        self.comboBox_skill.setItemText(3, _translate("HRM_Employee_view", "Property Management"))
        self.comboBox_skill.setItemText(4, _translate("HRM_Employee_view", "Catering Services"))
        self.comboBox_skill.setItemText(5, _translate("HRM_Employee_view", "Chef/Cook"))
        self.comboBox_skill.setItemText(6, _translate("HRM_Employee_view", "Engineer- Electrical"))
        self.comboBox_skill.setItemText(7, _translate("HRM_Employee_view", "Engineer- water"))
        self.comboBox_skill.setItemText(8, _translate("HRM_Employee_view", "Engineer- vehicle"))
        self.comboBox_skill.setItemText(9, _translate("HRM_Employee_view", "Engineer- constraction"))
        self.comboBox_skill.setItemText(10, _translate("HRM_Employee_view", "Engineer- Agriculture"))
        self.comboBox_skill.setItemText(11, _translate("HRM_Employee_view", "Engineer- computer"))
        self.comboBox_skill.setItemText(12, _translate("HRM_Employee_view", "Engineer- telecommunication"))
        self.groupBox_2.setStatusTip(_translate("HRM_Employee_view", "Select Employee Payment Mode choise"))
        self.groupBox_2.setTitle(_translate("HRM_Employee_view", "Payment Mode"))
        self.radioButton_day.setText(_translate("HRM_Employee_view", "per Day"))
        self.radioButton_hr.setText(_translate("HRM_Employee_view", "per Hour"))
        self.radioButton_wk5.setText(_translate("HRM_Employee_view", "per Week(5 days)"))
        self.radioButton_wk6.setText(_translate("HRM_Employee_view", "per Week(6 days)"))
        self.radioButton_wk7.setText(_translate("HRM_Employee_view", "per Week(7 days)"))
        self.radioButton_mth21.setText(_translate("HRM_Employee_view", "per Month(21 days)"))
        self.radioButton_mth25.setText(_translate("HRM_Employee_view", "per Month(25)"))
        self.groupBox.setTitle(_translate("HRM_Employee_view", "Availability"))
        self.radioButton_2.setText(_translate("HRM_Employee_view", "Immediatelly"))
        self.radioButton_5.setText(_translate("HRM_Employee_view", "a day Notice"))
        self.radioButton_3.setText(_translate("HRM_Employee_view", "two weeks Notice"))
        self.radioButton_4.setText(_translate("HRM_Employee_view", "a week Notice"))
        self.radioButton.setText(_translate("HRM_Employee_view", "a Month Notice"))
        self.groupBox_4.setStatusTip(_translate("HRM_Employee_view", "Select employee availability"))
        self.groupBox_4.setTitle(_translate("HRM_Employee_view", "Availability"))
        self.radioButton_imm.setText(_translate("HRM_Employee_view", "Immediatelly"))
        self.radioButton_aday.setText(_translate("HRM_Employee_view", "a day Notice"))
        self.radioButton_2wks.setText(_translate("HRM_Employee_view", "two weeks Notice"))
        self.radioButton_1wk.setText(_translate("HRM_Employee_view", "a week Notice"))
        self.radioButton_1mth.setText(_translate("HRM_Employee_view", "a Month Notice"))
        self.label_3.setText(_translate("HRM_Employee_view", "Experience :Years"))
        self.spinBox_experience.setStatusTip(_translate("HRM_Employee_view", "Select employee level of Experience"))
        self.label.setText(_translate("HRM_Employee_view", "Human Resource Managment System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("HRM_Employee_view", "Data Entry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("HRM_Employee_view", "Data View"))
        self.pushButton_reg.setText(_translate("HRM_Employee_view", "Register"))
        self.pushButton_delete.setText(_translate("HRM_Employee_view", "Delete"))
        self.pushButton_login.setText(_translate("HRM_Employee_view", "Reset"))
        self.pushButton_back.setText(_translate("HRM_Employee_view", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HRM_Employee_view = QtWidgets.QDialog()
    ui = Ui_HRM_Employee_view()
    ui.setupUi(HRM_Employee_view)
    HRM_Employee_view.show()
    sys.exit(app.exec_())

