# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employee.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HRM_Employee_view(object):
    def setupUi(self, HRM_Employee_view):
        HRM_Employee_view.setObjectName("HRM_Employee_view")
        HRM_Employee_view.resize(1382, 725)
        HRM_Employee_view.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HRM_Employee_view.setWindowIcon(icon)
        HRM_Employee_view.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.tabWidget = QtWidgets.QTabWidget(HRM_Employee_view)
        self.tabWidget.setGeometry(QtCore.QRect(20, 50, 1341, 581))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 1321, 521))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(890, 40, 421, 351))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 170, 210))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(170, 210))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 151, 185))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_day = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_day.setFont(font)
        self.radioButton_day.setObjectName("radioButton_day")
        self.verticalLayout.addWidget(self.radioButton_day)
        self.radioButton_hr = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_hr.setFont(font)
        self.radioButton_hr.setObjectName("radioButton_hr")
        self.verticalLayout.addWidget(self.radioButton_hr)
        self.radioButton_wk5 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_wk5.setFont(font)
        self.radioButton_wk5.setObjectName("radioButton_wk5")
        self.verticalLayout.addWidget(self.radioButton_wk5)
        self.radioButton_wk6 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_wk6.setFont(font)
        self.radioButton_wk6.setObjectName("radioButton_wk6")
        self.verticalLayout.addWidget(self.radioButton_wk6)
        self.radioButton_wk7 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_wk7.setFont(font)
        self.radioButton_wk7.setObjectName("radioButton_wk7")
        self.verticalLayout.addWidget(self.radioButton_wk7)
        self.radioButton_mth21 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_mth21.setFont(font)
        self.radioButton_mth21.setObjectName("radioButton_mth21")
        self.verticalLayout.addWidget(self.radioButton_mth21)
        self.radioButton_mth25 = QtWidgets.QRadioButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_mth25.setFont(font)
        self.radioButton_mth25.setObjectName("radioButton_mth25")
        self.verticalLayout.addWidget(self.radioButton_mth25)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_bank = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_bank.setGeometry(QtCore.QRect(110, 250, 291, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_bank.setFont(font)
        self.comboBox_bank.setObjectName("comboBox_bank")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.comboBox_bank.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(192, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_job_group = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_job_group.setGeometry(QtCore.QRect(270, 30, 131, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_job_group.setFont(font)
        self.comboBox_job_group.setObjectName("comboBox_job_group")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.comboBox_job_group.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 91, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_acc = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_acc.setGeometry(QtCore.QRect(120, 300, 271, 20))
        self.lineEdit_acc.setObjectName("lineEdit_acc")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(30, 140, 101, 21))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lineEdit_IDNo = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_IDNo.setGeometry(QtCore.QRect(30, 160, 237, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_IDNo.setFont(font)
        self.lineEdit_IDNo.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_IDNo.setObjectName("lineEdit_IDNo")
        self.lineEdit_hrm_code = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_hrm_code.setEnabled(False)
        self.lineEdit_hrm_code.setGeometry(QtCore.QRect(30, 210, 235, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_hrm_code.setFont(font)
        self.lineEdit_hrm_code.setObjectName("lineEdit_hrm_code")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(30, 190, 235, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_3)
        self.label_37.setGeometry(QtCore.QRect(30, 50, 161, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(30, 240, 235, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.lineEdit_kra_pin = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_kra_pin.setGeometry(QtCore.QRect(30, 260, 235, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_kra_pin.setFont(font)
        self.lineEdit_kra_pin.setInputMethodHints(QtCore.Qt.ImhPreferUppercase|QtCore.Qt.ImhUppercaseOnly)
        self.lineEdit_kra_pin.setMaxLength(32767)
        self.lineEdit_kra_pin.setObjectName("lineEdit_kra_pin")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(30, 290, 235, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_regNo = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_regNo.setEnabled(False)
        self.lineEdit_regNo.setGeometry(QtCore.QRect(30, 310, 235, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_regNo.setFont(font)
        self.lineEdit_regNo.setObjectName("lineEdit_regNo")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(340, 160, 292, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_11.addWidget(self.label_43)
        self.lineEdit_tell = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tell.sizePolicy().hasHeightForWidth())
        self.lineEdit_tell.setSizePolicy(sizePolicy)
        self.lineEdit_tell.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_tell.setFont(font)
        self.lineEdit_tell.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_tell.setObjectName("lineEdit_tell")
        self.horizontalLayout_11.addWidget(self.lineEdit_tell)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 50, 311, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_40 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_2.addWidget(self.label_40)
        self.lineEdit_fn = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_fn.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_fn.setFont(font)
        self.lineEdit_fn.setObjectName("lineEdit_fn")
        self.horizontalLayout_2.addWidget(self.lineEdit_fn)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(340, 80, 311, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_41 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_6.addWidget(self.label_41)
        self.lineEdit_mn = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_mn.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mn.setFont(font)
        self.lineEdit_mn.setObjectName("lineEdit_mn")
        self.horizontalLayout_6.addWidget(self.lineEdit_mn)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(340, 110, 311, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_42 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_7.addWidget(self.label_42)
        self.lineEdit_ln = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_ln.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_ln.setFont(font)
        self.lineEdit_ln.setObjectName("lineEdit_ln")
        self.horizontalLayout_7.addWidget(self.lineEdit_ln)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(340, 190, 353, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_10.addWidget(self.label_44)
        self.lineEdit_email = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_email.sizePolicy().hasHeightForWidth())
        self.lineEdit_email.setSizePolicy(sizePolicy)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_10.addWidget(self.lineEdit_email)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(660, 120, 221, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_45 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_4.addWidget(self.label_45)
        self.radioButton_m = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_m.setFont(font)
        self.radioButton_m.setObjectName("radioButton_m")
        self.horizontalLayout_4.addWidget(self.radioButton_m)
        self.radioButton_f = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_f.setFont(font)
        self.radioButton_f.setObjectName("radioButton_f")
        self.horizontalLayout_4.addWidget(self.radioButton_f)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(660, 50, 224, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_3.addWidget(self.label_46)
        self.dateEdit_dob = QtWidgets.QDateEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_dob.setFont(font)
        self.dateEdit_dob.setMaximumDate(QtCore.QDate(2018, 9, 14))
        self.dateEdit_dob.setMinimumDate(QtCore.QDate(1920, 9, 14))
        self.dateEdit_dob.setCalendarPopup(True)
        self.dateEdit_dob.setObjectName("dateEdit_dob")
        self.horizontalLayout_3.addWidget(self.dateEdit_dob)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(510, 290, 291, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.spinBox_experience = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_experience.setObjectName("spinBox_experience")
        self.horizontalLayout_13.addWidget(self.spinBox_experience)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(30, 340, 261, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_pobox = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_pobox.setGeometry(QtCore.QRect(120, 100, 131, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pobox.setFont(font)
        self.lineEdit_pobox.setObjectName("lineEdit_pobox")
        self.lineEdit_pcode = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_pcode.setGeometry(QtCore.QRect(120, 140, 131, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_pcode.setFont(font)
        self.lineEdit_pcode.setObjectName("lineEdit_pcode")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_3.setGeometry(QtCore.QRect(80, 20, 171, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 81, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 91, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_region = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_region.setGeometry(QtCore.QRect(120, 60, 131, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_region.setFont(font)
        self.lineEdit_region.setObjectName("lineEdit_region")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(330, 280, 160, 160))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(160, 160))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 20, 137, 131))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.radioButton_imm = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_imm.setFont(font)
        self.radioButton_imm.setObjectName("radioButton_imm")
        self.verticalLayout_12.addWidget(self.radioButton_imm)
        self.radioButton_aday = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_aday.setFont(font)
        self.radioButton_aday.setObjectName("radioButton_aday")
        self.verticalLayout_12.addWidget(self.radioButton_aday)
        self.radioButton_2wks = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2wks.setFont(font)
        self.radioButton_2wks.setObjectName("radioButton_2wks")
        self.verticalLayout_12.addWidget(self.radioButton_2wks)
        self.radioButton_1wk = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_1wk.setFont(font)
        self.radioButton_1wk.setObjectName("radioButton_1wk")
        self.verticalLayout_12.addWidget(self.radioButton_1wk)
        self.radioButton_1mth = QtWidgets.QRadioButton(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_1mth.setFont(font)
        self.radioButton_1mth.setObjectName("radioButton_1mth")
        self.verticalLayout_12.addWidget(self.radioButton_1mth)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(430, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(340, 250, 431, 22))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_skill = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_skill.sizePolicy().hasHeightForWidth())
        self.comboBox_skill.setSizePolicy(sizePolicy)
        self.comboBox_skill.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_skill.setFont(font)
        self.comboBox_skill.setObjectName("comboBox_skill")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.comboBox_skill.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_skill)
        self.pushButton_reg = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_reg.setGeometry(QtCore.QRect(1180, 450, 107, 48))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_reg.setFont(font)
        self.pushButton_reg.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/icons/coin-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reg.setIcon(icon1)
        self.pushButton_reg.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.label_timestamp = QtWidgets.QLabel(self.groupBox_3)
        self.label_timestamp.setGeometry(QtCore.QRect(30, 70, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_timestamp.setFont(font)
        self.label_timestamp.setLineWidth(1)
        self.label_timestamp.setText("")
        self.label_timestamp.setScaledContents(True)
        self.label_timestamp.setWordWrap(True)
        self.label_timestamp.setObjectName("label_timestamp")
        self.lcdNumber_user_id = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_user_id.setGeometry(QtCore.QRect(1200, 10, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_user_id.sizePolicy().hasHeightForWidth())
        self.lcdNumber_user_id.setSizePolicy(sizePolicy)
        self.lcdNumber_user_id.setMinimumSize(QtCore.QSize(31, 24))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_user_id.setFont(font)
        self.lcdNumber_user_id.setObjectName("lcdNumber_user_id")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/businessman-4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_6)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1311, 531))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.tableWidget_records = QtWidgets.QTableView(self.formLayoutWidget_2)
        self.tableWidget_records.setMinimumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_records.setFont(font)
        self.tableWidget_records.setAutoFillBackground(True)
        self.tableWidget_records.setStyleSheet("background-color:rgb(121, 255, 175)")
        self.tableWidget_records.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget_records.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_records.setLineWidth(4)
        self.tableWidget_records.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget_records.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_records.setAlternatingRowColors(True)
        self.tableWidget_records.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_records.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_records.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_records.setSortingEnabled(True)
        self.tableWidget_records.setObjectName("tableWidget_records")
        self.tableWidget_records.horizontalHeader().setDefaultSectionSize(200)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tableWidget_records)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/businessman-6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon3, "")
        self.line = QtWidgets.QFrame(HRM_Employee_view)
        self.line.setGeometry(QtCore.QRect(20, 30, 1351, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(HRM_Employee_view)
        self.line_3.setGeometry(QtCore.QRect(20, 680, 1351, 16))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.label = QtWidgets.QLabel(HRM_Employee_view)
        self.label.setGeometry(QtCore.QRect(700, 30, 501, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton_back = QtWidgets.QPushButton(HRM_Employee_view)
        self.pushButton_back.setGeometry(QtCore.QRect(1060, 630, 111, 48))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_back.setFont(font)
        self.pushButton_back.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/icons/web-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back.setIcon(icon4)
        self.pushButton_back.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_back.setObjectName("pushButton_back")
        self.label_35.setBuddy(self.lineEdit_IDNo)
        self.label_36.setBuddy(self.lineEdit_hrm_code)
        self.label_38.setBuddy(self.lineEdit_kra_pin)
        self.label_18.setBuddy(self.lineEdit_regNo)
        self.label_43.setBuddy(self.lineEdit_tell)
        self.label_40.setBuddy(self.lineEdit_fn)
        self.label_41.setBuddy(self.lineEdit_mn)
        self.label_42.setBuddy(self.lineEdit_ln)
        self.label_44.setBuddy(self.lineEdit_email)
        self.label_45.setBuddy(self.radioButton_f)
        self.label_46.setBuddy(self.dateEdit_dob)
        self.label_2.setBuddy(self.comboBox_skill)

        self.retranslateUi(HRM_Employee_view)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_skill.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HRM_Employee_view)
        HRM_Employee_view.setTabOrder(self.lineEdit_IDNo, self.lineEdit_kra_pin)
        HRM_Employee_view.setTabOrder(self.lineEdit_kra_pin, self.comboBox_3)
        HRM_Employee_view.setTabOrder(self.comboBox_3, self.lineEdit_pobox)
        HRM_Employee_view.setTabOrder(self.lineEdit_pobox, self.lineEdit_pcode)
        HRM_Employee_view.setTabOrder(self.lineEdit_pcode, self.lineEdit_fn)
        HRM_Employee_view.setTabOrder(self.lineEdit_fn, self.lineEdit_mn)
        HRM_Employee_view.setTabOrder(self.lineEdit_mn, self.lineEdit_ln)
        HRM_Employee_view.setTabOrder(self.lineEdit_ln, self.lineEdit_tell)
        HRM_Employee_view.setTabOrder(self.lineEdit_tell, self.lineEdit_email)
        HRM_Employee_view.setTabOrder(self.lineEdit_email, self.comboBox_skill)
        HRM_Employee_view.setTabOrder(self.comboBox_skill, self.dateEdit_dob)
        HRM_Employee_view.setTabOrder(self.dateEdit_dob, self.radioButton_m)
        HRM_Employee_view.setTabOrder(self.radioButton_m, self.radioButton_f)
        HRM_Employee_view.setTabOrder(self.radioButton_f, self.comboBox_job_group)
        HRM_Employee_view.setTabOrder(self.comboBox_job_group, self.comboBox_bank)
        HRM_Employee_view.setTabOrder(self.comboBox_bank, self.lineEdit_acc)
        HRM_Employee_view.setTabOrder(self.lineEdit_acc, self.radioButton_imm)
        HRM_Employee_view.setTabOrder(self.radioButton_imm, self.radioButton_aday)
        HRM_Employee_view.setTabOrder(self.radioButton_aday, self.radioButton_2wks)
        HRM_Employee_view.setTabOrder(self.radioButton_2wks, self.radioButton_1wk)
        HRM_Employee_view.setTabOrder(self.radioButton_1wk, self.radioButton_1mth)
        HRM_Employee_view.setTabOrder(self.radioButton_1mth, self.radioButton_day)
        HRM_Employee_view.setTabOrder(self.radioButton_day, self.radioButton_hr)
        HRM_Employee_view.setTabOrder(self.radioButton_hr, self.radioButton_wk5)
        HRM_Employee_view.setTabOrder(self.radioButton_wk5, self.radioButton_wk6)
        HRM_Employee_view.setTabOrder(self.radioButton_wk6, self.radioButton_wk7)
        HRM_Employee_view.setTabOrder(self.radioButton_wk7, self.radioButton_mth21)
        HRM_Employee_view.setTabOrder(self.radioButton_mth21, self.radioButton_mth25)
        HRM_Employee_view.setTabOrder(self.radioButton_mth25, self.spinBox_experience)
        HRM_Employee_view.setTabOrder(self.spinBox_experience, self.pushButton_reg)
        HRM_Employee_view.setTabOrder(self.pushButton_reg, self.tabWidget)
        HRM_Employee_view.setTabOrder(self.tabWidget, self.tableWidget_records)
        HRM_Employee_view.setTabOrder(self.tableWidget_records, self.lineEdit_hrm_code)
        HRM_Employee_view.setTabOrder(self.lineEdit_hrm_code, self.lineEdit_regNo)

    def retranslateUi(self, HRM_Employee_view):
        _translate = QtCore.QCoreApplication.translate
        HRM_Employee_view.setWindowTitle(_translate("HRM_Employee_view", "HRM Employee Registration Form"))
        self.groupBox_3.setTitle(_translate("HRM_Employee_view", "Enter New Employee  Details"))
        self.groupBox_5.setTitle(_translate("HRM_Employee_view", "Payments"))
        self.groupBox_2.setStatusTip(_translate("HRM_Employee_view", "Select Employee Payment Mode choise"))
        self.groupBox_2.setTitle(_translate("HRM_Employee_view", "Payment Mode"))
        self.radioButton_day.setText(_translate("HRM_Employee_view", "per Day"))
        self.radioButton_hr.setText(_translate("HRM_Employee_view", "per Hour"))
        self.radioButton_wk5.setText(_translate("HRM_Employee_view", "per Week(5 days)"))
        self.radioButton_wk6.setText(_translate("HRM_Employee_view", "per Week(6 days)"))
        self.radioButton_wk7.setText(_translate("HRM_Employee_view", "per Week(7 days)"))
        self.radioButton_mth21.setText(_translate("HRM_Employee_view", "per Month(21 days)"))
        self.radioButton_mth25.setText(_translate("HRM_Employee_view", "per Month(25)"))
        self.label_4.setText(_translate("HRM_Employee_view", "Banking :"))
        self.comboBox_bank.setItemText(0, _translate("HRM_Employee_view", "None"))
        self.comboBox_bank.setItemText(1, _translate("HRM_Employee_view", "National Bank"))
        self.comboBox_bank.setItemText(2, _translate("HRM_Employee_view", "KCB"))
        self.comboBox_bank.setItemText(3, _translate("HRM_Employee_view", "Transnational Bank"))
        self.comboBox_bank.setItemText(4, _translate("HRM_Employee_view", "Barclays"))
        self.comboBox_bank.setItemText(5, _translate("HRM_Employee_view", "Co-operative Bank"))
        self.comboBox_bank.setItemText(6, _translate("HRM_Employee_view", "Standard Chattered Bank"))
        self.comboBox_bank.setItemText(7, _translate("HRM_Employee_view", "Equity Bank"))
        self.comboBox_bank.setItemText(8, _translate("HRM_Employee_view", "Family Bank"))
        self.comboBox_bank.setItemText(9, _translate("HRM_Employee_view", "Diamond Trust Bank"))
        self.comboBox_bank.setItemText(10, _translate("HRM_Employee_view", "abc Bank"))
        self.comboBox_bank.setItemText(11, _translate("HRM_Employee_view", "Chase Bank"))
        self.comboBox_bank.setItemText(12, _translate("HRM_Employee_view", "Eco Bank"))
        self.comboBox_bank.setItemText(13, _translate("HRM_Employee_view", "I&M Bank"))
        self.comboBox_bank.setItemText(14, _translate("HRM_Employee_view", "K-Rep Bank"))
        self.comboBox_bank.setItemText(15, _translate("HRM_Employee_view", "NIC Bank"))
        self.comboBox_bank.setItemText(16, _translate("HRM_Employee_view", "Post Bank"))
        self.comboBox_bank.setItemText(17, _translate("HRM_Employee_view", "M-pesa"))
        self.label_5.setText(_translate("HRM_Employee_view", "Job Group:"))
        self.comboBox_job_group.setItemText(0, _translate("HRM_Employee_view", "None"))
        self.comboBox_job_group.setItemText(1, _translate("HRM_Employee_view", "H"))
        self.comboBox_job_group.setItemText(2, _translate("HRM_Employee_view", "G"))
        self.comboBox_job_group.setItemText(3, _translate("HRM_Employee_view", "F"))
        self.comboBox_job_group.setItemText(4, _translate("HRM_Employee_view", "E"))
        self.comboBox_job_group.setItemText(5, _translate("HRM_Employee_view", "D"))
        self.comboBox_job_group.setItemText(6, _translate("HRM_Employee_view", "C"))
        self.comboBox_job_group.setItemText(7, _translate("HRM_Employee_view", "B"))
        self.comboBox_job_group.setItemText(8, _translate("HRM_Employee_view", "A"))
        self.label_6.setText(_translate("HRM_Employee_view", "Account No. :"))
        self.label_35.setText(_translate("HRM_Employee_view", "National ID No."))
        self.lineEdit_IDNo.setStatusTip(_translate("HRM_Employee_view", "Enter Employee National ID Number"))
        self.lineEdit_hrm_code.setStatusTip(_translate("HRM_Employee_view", "Auto filled Employee system Code"))
        self.label_36.setText(_translate("HRM_Employee_view", "Employee HRM Code :"))
        self.label_37.setText(_translate("HRM_Employee_view", "Registration Date Stamp"))
        self.label_38.setText(_translate("HRM_Employee_view", "KRA PIN"))
        self.lineEdit_kra_pin.setStatusTip(_translate("HRM_Employee_view", "Enter Kenya Revenue of Authority Personal Identification Number"))
        self.label_18.setText(_translate("HRM_Employee_view", "Registration Number:"))
        self.lineEdit_regNo.setStatusTip(_translate("HRM_Employee_view", "Auto filled user registration number"))
        self.label_43.setText(_translate("HRM_Employee_view", "Phone Number :"))
        self.lineEdit_tell.setStatusTip(_translate("HRM_Employee_view", "Enter Employee Phone Number"))
        self.label_40.setText(_translate("HRM_Employee_view", "First Name :"))
        self.lineEdit_fn.setStatusTip(_translate("HRM_Employee_view", "Enter Employee First Name"))
        self.label_41.setText(_translate("HRM_Employee_view", "Middle Name :"))
        self.lineEdit_mn.setStatusTip(_translate("HRM_Employee_view", "Enter Employee First Name"))
        self.label_42.setText(_translate("HRM_Employee_view", "Last Name :"))
        self.lineEdit_ln.setStatusTip(_translate("HRM_Employee_view", "Enter Employee First Name"))
        self.label_44.setText(_translate("HRM_Employee_view", "Email :"))
        self.lineEdit_email.setStatusTip(_translate("HRM_Employee_view", "Enter Employee Email address"))
        self.label_45.setStatusTip(_translate("HRM_Employee_view", "Select User Gender"))
        self.label_45.setText(_translate("HRM_Employee_view", "Gender"))
        self.radioButton_m.setText(_translate("HRM_Employee_view", "Male"))
        self.radioButton_f.setText(_translate("HRM_Employee_view", "Female"))
        self.label_46.setText(_translate("HRM_Employee_view", "Date Of Birth :"))
        self.dateEdit_dob.setStatusTip(_translate("HRM_Employee_view", "Select Employee date of Birth"))
        self.dateEdit_dob.setDisplayFormat(_translate("HRM_Employee_view", "d/M/yyyy"))
        self.label_3.setText(_translate("HRM_Employee_view", "Experience :Years"))
        self.spinBox_experience.setStatusTip(_translate("HRM_Employee_view", "Select employee level of Experience"))
        self.groupBox.setTitle(_translate("HRM_Employee_view", "Address :"))
        self.comboBox_3.setItemText(0, _translate("HRM_Employee_view", "Nakuru"))
        self.comboBox_3.setItemText(1, _translate("HRM_Employee_view", "Nairobi"))
        self.comboBox_3.setItemText(2, _translate("HRM_Employee_view", "Eldoret"))
        self.comboBox_3.setItemText(3, _translate("HRM_Employee_view", "Mombasa"))
        self.label_7.setText(_translate("HRM_Employee_view", "County :"))
        self.label_8.setText(_translate("HRM_Employee_view", "Region :"))
        self.label_9.setText(_translate("HRM_Employee_view", "P.O Box :"))
        self.label_10.setText(_translate("HRM_Employee_view", "Postal Code :"))
        self.groupBox_4.setStatusTip(_translate("HRM_Employee_view", "Select employee availability"))
        self.groupBox_4.setTitle(_translate("HRM_Employee_view", "Availability"))
        self.radioButton_imm.setText(_translate("HRM_Employee_view", "Immediatelly"))
        self.radioButton_aday.setText(_translate("HRM_Employee_view", "a day Notice"))
        self.radioButton_2wks.setText(_translate("HRM_Employee_view", "two weeks Notice"))
        self.radioButton_1wk.setText(_translate("HRM_Employee_view", "a week Notice"))
        self.radioButton_1mth.setText(_translate("HRM_Employee_view", "a Month Notice"))
        self.label_11.setText(_translate("HRM_Employee_view", "New Employee Registration"))
        self.label_2.setText(_translate("HRM_Employee_view", "Skill- Set Category"))
        self.comboBox_skill.setToolTip(_translate("HRM_Employee_view", "Select a Speciallity Category..."))
        self.comboBox_skill.setStatusTip(_translate("HRM_Employee_view", "Select worker skill set"))
        self.comboBox_skill.setCurrentText(_translate("HRM_Employee_view", "None"))
        self.comboBox_skill.setItemText(0, _translate("HRM_Employee_view", "None"))
        self.comboBox_skill.setItemText(1, _translate("HRM_Employee_view", "House Keeping"))
        self.comboBox_skill.setItemText(2, _translate("HRM_Employee_view", "Personal/Property Security"))
        self.comboBox_skill.setItemText(3, _translate("HRM_Employee_view", "Property Management"))
        self.comboBox_skill.setItemText(4, _translate("HRM_Employee_view", "Catering Services"))
        self.comboBox_skill.setItemText(5, _translate("HRM_Employee_view", "Chef/Cook"))
        self.comboBox_skill.setItemText(6, _translate("HRM_Employee_view", "Engineer- Electrical"))
        self.comboBox_skill.setItemText(7, _translate("HRM_Employee_view", "Engineer- water"))
        self.comboBox_skill.setItemText(8, _translate("HRM_Employee_view", "Engineer- vehicle"))
        self.comboBox_skill.setItemText(9, _translate("HRM_Employee_view", "Engineer- constraction"))
        self.comboBox_skill.setItemText(10, _translate("HRM_Employee_view", "Engineer- Agriculture"))
        self.comboBox_skill.setItemText(11, _translate("HRM_Employee_view", "Engineer- computer"))
        self.comboBox_skill.setItemText(12, _translate("HRM_Employee_view", "Engineer- telecommunication"))
        self.pushButton_reg.setText(_translate("HRM_Employee_view", "Register"))
        self.lcdNumber_user_id.setStatusTip(_translate("HRM_Employee_view", "Auto count the number of Employees in the system"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("HRM_Employee_view", "Data Entry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("HRM_Employee_view", "Data View"))
        self.label.setText(_translate("HRM_Employee_view", "Human Resource Managment System"))
        self.pushButton_back.setText(_translate("HRM_Employee_view", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HRM_Employee_view = QtWidgets.QDialog()
    ui = Ui_HRM_Employee_view()
    ui.setupUi(HRM_Employee_view)
    HRM_Employee_view.show()
    sys.exit(app.exec_())

