# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HRM_Login_view(object):
    def setupUi(self, HRM_Login_view):
        HRM_Login_view.setObjectName("HRM_Login_view")
        HRM_Login_view.resize(851, 474)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HRM_Login_view.setWindowIcon(icon)
        HRM_Login_view.setStyleSheet("background-color:rgb(40, 93, 117);color:rgb(0, 255, 255)")
        self.label = QtWidgets.QLabel(HRM_Login_view)
        self.label.setGeometry(QtCore.QRect(340, 40, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Playbill")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(HRM_Login_view)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 420, 621, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_login = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout.addWidget(self.pushButton_login)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_signup = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.pushButton_signup.setFont(font)
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.horizontalLayout.addWidget(self.pushButton_signup)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_back = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("System")
        self.pushButton_back.setFont(font)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout.addWidget(self.pushButton_back)
        self.layoutWidget1 = QtWidgets.QWidget(HRM_Login_view)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 140, 691, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_un = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_un.setObjectName("lineEdit_un")
        self.horizontalLayout_2.addWidget(self.lineEdit_un)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_pass = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.horizontalLayout_3.addWidget(self.lineEdit_pass)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label_4 = QtWidgets.QLabel(HRM_Login_view)
        self.label_4.setGeometry(QtCore.QRect(100, 270, 701, 81))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(HRM_Login_view)
        QtCore.QMetaObject.connectSlotsByName(HRM_Login_view)

    def retranslateUi(self, HRM_Login_view):
        _translate = QtCore.QCoreApplication.translate
        HRM_Login_view.setWindowTitle(_translate("HRM_Login_view", "User Login Form"))
        self.label.setText(_translate("HRM_Login_view", "User Login"))
        self.pushButton_login.setStatusTip(_translate("HRM_Login_view", "Have An account"))
        self.pushButton_login.setText(_translate("HRM_Login_view", "Login"))
        self.pushButton_signup.setStatusTip(_translate("HRM_Login_view", "New system User"))
        self.pushButton_signup.setText(_translate("HRM_Login_view", "Create Account"))
        self.pushButton_back.setStatusTip(_translate("HRM_Login_view", "Back to Website"))
        self.pushButton_back.setText(_translate("HRM_Login_view", "Back"))
        self.lineEdit_un.setStatusTip(_translate("HRM_Login_view", "Please Enter your User Name"))
        self.lineEdit_un.setPlaceholderText(_translate("HRM_Login_view", "Enter your User Name"))
        self.lineEdit_pass.setStatusTip(_translate("HRM_Login_view", "Please Enter your Password"))
        self.lineEdit_pass.setPlaceholderText(_translate("HRM_Login_view", "Enter your Password"))
        self.label_4.setText(_translate("HRM_Login_view", "Human Resource Managment System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HRM_Login_view = QtWidgets.QDialog()
    ui = Ui_HRM_Login_view()
    ui.setupUi(HRM_Login_view)
    HRM_Login_view.show()
    sys.exit(app.exec_())

