# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payroll.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_payrolDialog(object):
    def setupUi(self, payrolDialog):
        payrolDialog.setObjectName("payrolDialog")
        payrolDialog.resize(1077, 706)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        payrolDialog.setWindowIcon(icon)
        payrolDialog.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.label_org_name = QtWidgets.QLabel(payrolDialog)
        self.label_org_name.setGeometry(QtCore.QRect(240, 30, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_org_name.setFont(font)
        self.label_org_name.setObjectName("label_org_name")
        self.label_2 = QtWidgets.QLabel(payrolDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_employee_name = QtWidgets.QLabel(payrolDialog)
        self.label_employee_name.setGeometry(QtCore.QRect(390, 120, 331, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_employee_name.setFont(font)
        self.label_employee_name.setObjectName("label_employee_name")
        self.label_4 = QtWidgets.QLabel(payrolDialog)
        self.label_4.setGeometry(QtCore.QRect(30, 150, 47, 13))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_station_loc = QtWidgets.QLabel(payrolDialog)
        self.label_station_loc.setGeometry(QtCore.QRect(110, 150, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_station_loc.setFont(font)
        self.label_station_loc.setObjectName("label_station_loc")
        self.label_station_no = QtWidgets.QLabel(payrolDialog)
        self.label_station_no.setGeometry(QtCore.QRect(110, 180, 291, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_station_no.setFont(font)
        self.label_station_no.setObjectName("label_station_no")
        self.label_7 = QtWidgets.QLabel(payrolDialog)
        self.label_7.setGeometry(QtCore.QRect(30, 220, 91, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_id_no = QtWidgets.QLabel(payrolDialog)
        self.label_id_no.setGeometry(QtCore.QRect(110, 220, 91, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_id_no.setFont(font)
        self.label_id_no.setObjectName("label_id_no")
        self.label_age = QtWidgets.QLabel(payrolDialog)
        self.label_age.setGeometry(QtCore.QRect(740, 160, 47, 13))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_age.setFont(font)
        self.label_age.setObjectName("label_age")
        self.label_15 = QtWidgets.QLabel(payrolDialog)
        self.label_15.setGeometry(QtCore.QRect(280, 260, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(payrolDialog)
        self.label_17.setGeometry(QtCore.QRect(270, 650, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.groupBox_2 = QtWidgets.QGroupBox(payrolDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 310, 441, 311))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_nssf = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_nssf.setGeometry(QtCore.QRect(10, 30, 131, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nssf.setFont(font)
        self.checkBox_nssf.setChecked(False)
        self.checkBox_nssf.setObjectName("checkBox_nssf")
        self.checkBox_nhif = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_nhif.setGeometry(QtCore.QRect(10, 60, 171, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_nhif.setFont(font)
        self.checkBox_nhif.setChecked(False)
        self.checkBox_nhif.setObjectName("checkBox_nhif")
        self.checkBox_paye = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_paye.setGeometry(QtCore.QRect(10, 90, 121, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_paye.setFont(font)
        self.checkBox_paye.setChecked(False)
        self.checkBox_paye.setObjectName("checkBox_paye")
        self.checkBox_insuarance_premium = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_insuarance_premium.setGeometry(QtCore.QRect(10, 120, 301, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_insuarance_premium.setFont(font)
        self.checkBox_insuarance_premium.setChecked(False)
        self.checkBox_insuarance_premium.setObjectName("checkBox_insuarance_premium")
        self.checkBox_provident_pension = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_provident_pension.setGeometry(QtCore.QRect(10, 150, 281, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_provident_pension.setFont(font)
        self.checkBox_provident_pension.setChecked(False)
        self.checkBox_provident_pension.setObjectName("checkBox_provident_pension")
        self.checkBox_voluntary_pension = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_voluntary_pension.setGeometry(QtCore.QRect(10, 180, 141, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_voluntary_pension.setFont(font)
        self.checkBox_voluntary_pension.setChecked(False)
        self.checkBox_voluntary_pension.setObjectName("checkBox_voluntary_pension")
        self.checkBox_loans = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_loans.setGeometry(QtCore.QRect(10, 210, 131, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_loans.setFont(font)
        self.checkBox_loans.setChecked(False)
        self.checkBox_loans.setObjectName("checkBox_loans")
        self.label_nssf = QtWidgets.QLabel(self.groupBox_2)
        self.label_nssf.setGeometry(QtCore.QRect(350, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_nssf.setFont(font)
        self.label_nssf.setObjectName("label_nssf")
        self.label_nhif = QtWidgets.QLabel(self.groupBox_2)
        self.label_nhif.setGeometry(QtCore.QRect(350, 60, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_nhif.setFont(font)
        self.label_nhif.setObjectName("label_nhif")
        self.label_paye = QtWidgets.QLabel(self.groupBox_2)
        self.label_paye.setGeometry(QtCore.QRect(350, 90, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_paye.setFont(font)
        self.label_paye.setObjectName("label_paye")
        self.label_insuarance_premium = QtWidgets.QLabel(self.groupBox_2)
        self.label_insuarance_premium.setGeometry(QtCore.QRect(350, 120, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_insuarance_premium.setFont(font)
        self.label_insuarance_premium.setObjectName("label_insuarance_premium")
        self.label_provident_pension = QtWidgets.QLabel(self.groupBox_2)
        self.label_provident_pension.setGeometry(QtCore.QRect(350, 150, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_provident_pension.setFont(font)
        self.label_provident_pension.setObjectName("label_provident_pension")
        self.label_voluntary_pension = QtWidgets.QLabel(self.groupBox_2)
        self.label_voluntary_pension.setGeometry(QtCore.QRect(350, 180, 71, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_voluntary_pension.setFont(font)
        self.label_voluntary_pension.setObjectName("label_voluntary_pension")
        self.label_loan = QtWidgets.QLabel(self.groupBox_2)
        self.label_loan.setGeometry(QtCore.QRect(350, 210, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_loan.setFont(font)
        self.label_loan.setObjectName("label_loan")
        self.label_total_deductions = QtWidgets.QLabel(self.groupBox_2)
        self.label_total_deductions.setGeometry(QtCore.QRect(350, 250, 81, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_total_deductions.setFont(font)
        self.label_total_deductions.setStyleSheet("color:rgb(170, 0, 0)")
        self.label_total_deductions.setObjectName("label_total_deductions")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 250, 131, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(10, 230, 401, 16))
        self.line_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setGeometry(QtCore.QRect(10, 270, 401, 16))
        self.line_4.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.label_pfnum = QtWidgets.QLabel(payrolDialog)
        self.label_pfnum.setGeometry(QtCore.QRect(110, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_pfnum.setFont(font)
        self.label_pfnum.setObjectName("label_pfnum")
        self.label_31 = QtWidgets.QLabel(payrolDialog)
        self.label_31.setGeometry(QtCore.QRect(320, 120, 47, 13))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(payrolDialog)
        self.label_32.setGeometry(QtCore.QRect(320, 220, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_kra_pin = QtWidgets.QLabel(payrolDialog)
        self.label_kra_pin.setGeometry(QtCore.QRect(390, 220, 101, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_kra_pin.setFont(font)
        self.label_kra_pin.setObjectName("label_kra_pin")
        self.label_34 = QtWidgets.QLabel(payrolDialog)
        self.label_34.setGeometry(QtCore.QRect(680, 160, 47, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_bank_name = QtWidgets.QLabel(payrolDialog)
        self.label_bank_name.setGeometry(QtCore.QRect(400, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_bank_name.setFont(font)
        self.label_bank_name.setObjectName("label_bank_name")
        self.label_net_pay = QtWidgets.QLabel(payrolDialog)
        self.label_net_pay.setGeometry(QtCore.QRect(360, 650, 201, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_net_pay.setFont(font)
        self.label_net_pay.setObjectName("label_net_pay")
        self.line_5 = QtWidgets.QFrame(payrolDialog)
        self.line_5.setGeometry(QtCore.QRect(270, 670, 421, 16))
        self.line_5.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(payrolDialog)
        self.line_6.setGeometry(QtCore.QRect(20, 290, 851, 16))
        self.line_6.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(payrolDialog)
        self.line_7.setGeometry(QtCore.QRect(20, 100, 851, 16))
        self.line_7.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.pushButton = QtWidgets.QPushButton(payrolDialog)
        self.pushButton.setGeometry(QtCore.QRect(860, 640, 75, 23))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(payrolDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 400, 351, 221))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox_bsalary = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_bsalary.setEnabled(True)
        self.checkBox_bsalary.setGeometry(QtCore.QRect(10, 20, 131, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_bsalary.setFont(font)
        self.checkBox_bsalary.setChecked(False)
        self.checkBox_bsalary.setObjectName("checkBox_bsalary")
        self.checkBox_hse_allowance = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_hse_allowance.setGeometry(QtCore.QRect(10, 80, 191, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_hse_allowance.setFont(font)
        self.checkBox_hse_allowance.setChecked(False)
        self.checkBox_hse_allowance.setObjectName("checkBox_hse_allowance")
        self.checkBox_med_allowance = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_med_allowance.setGeometry(QtCore.QRect(10, 110, 191, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_med_allowance.setFont(font)
        self.checkBox_med_allowance.setChecked(False)
        self.checkBox_med_allowance.setObjectName("checkBox_med_allowance")
        self.checkBox_oth_allowance = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_oth_allowance.setGeometry(QtCore.QRect(10, 140, 161, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_oth_allowance.setFont(font)
        self.checkBox_oth_allowance.setChecked(False)
        self.checkBox_oth_allowance.setObjectName("checkBox_oth_allowance")
        self.label_bsalary = QtWidgets.QLabel(self.groupBox)
        self.label_bsalary.setGeometry(QtCore.QRect(260, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_bsalary.setFont(font)
        self.label_bsalary.setObjectName("label_bsalary")
        self.label_hse_allowance = QtWidgets.QLabel(self.groupBox)
        self.label_hse_allowance.setGeometry(QtCore.QRect(260, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_hse_allowance.setFont(font)
        self.label_hse_allowance.setObjectName("label_hse_allowance")
        self.label_med_allowance = QtWidgets.QLabel(self.groupBox)
        self.label_med_allowance.setGeometry(QtCore.QRect(260, 110, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_med_allowance.setFont(font)
        self.label_med_allowance.setObjectName("label_med_allowance")
        self.label_oth_allowance = QtWidgets.QLabel(self.groupBox)
        self.label_oth_allowance.setGeometry(QtCore.QRect(260, 140, 61, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_oth_allowance.setFont(font)
        self.label_oth_allowance.setObjectName("label_oth_allowance")
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setGeometry(QtCore.QRect(10, 180, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_gross_salary = QtWidgets.QLabel(self.groupBox)
        self.label_gross_salary.setGeometry(QtCore.QRect(260, 180, 61, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_gross_salary.setFont(font)
        self.label_gross_salary.setStyleSheet("color:rgb(85, 170, 0)")
        self.label_gross_salary.setObjectName("label_gross_salary")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 160, 291, 16))
        self.line.setStyleSheet("color:rgb(0, 0, 0)")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(10, 200, 291, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color:rgb(0, 0, 0)")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 121, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(266, 50, 61, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(payrolDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(960, 640, 71, 23))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(payrolDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 310, 341, 91))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 40, 82, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 40, 82, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(190, 40, 111, 17))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")

        self.retranslateUi(payrolDialog)
        QtCore.QMetaObject.connectSlotsByName(payrolDialog)

    def retranslateUi(self, payrolDialog):
        _translate = QtCore.QCoreApplication.translate
        payrolDialog.setWindowTitle(_translate("payrolDialog", "Payroll Processing"))
        self.label_org_name.setText(_translate("payrolDialog", "Organization Name"))
        self.label_2.setText(_translate("payrolDialog", "PF-Num:"))
        self.label_employee_name.setText(_translate("payrolDialog", "None"))
        self.label_4.setText(_translate("payrolDialog", "Station:"))
        self.label_station_loc.setText(_translate("payrolDialog", "Location: None"))
        self.label_station_no.setText(_translate("payrolDialog", "Station No.:"))
        self.label_7.setText(_translate("payrolDialog", "ID- Number:"))
        self.label_id_no.setText(_translate("payrolDialog", "123456789"))
        self.label_age.setText(_translate("payrolDialog", "28"))
        self.label_15.setText(_translate("payrolDialog", "Banking:"))
        self.label_17.setText(_translate("payrolDialog", "Net Pay:"))
        self.groupBox_2.setTitle(_translate("payrolDialog", "Deductions"))
        self.checkBox_nssf.setText(_translate("payrolDialog", "NSSF Auto"))
        self.checkBox_nhif.setText(_translate("payrolDialog", "NHIF contribution"))
        self.checkBox_paye.setText(_translate("payrolDialog", "PAYE Auto"))
        self.checkBox_insuarance_premium.setText(_translate("payrolDialog", "Insuarance Premium Policy"))
        self.checkBox_provident_pension.setText(_translate("payrolDialog", "Provident Fund/ Pension"))
        self.checkBox_voluntary_pension.setText(_translate("payrolDialog", "Pension Voluntary"))
        self.checkBox_loans.setText(_translate("payrolDialog", "Loans"))
        self.label_nssf.setText(_translate("payrolDialog", "5,410"))
        self.label_nhif.setText(_translate("payrolDialog", "8,720"))
        self.label_paye.setText(_translate("payrolDialog", "9,875"))
        self.label_insuarance_premium.setText(_translate("payrolDialog", "6,000"))
        self.label_provident_pension.setText(_translate("payrolDialog", "4,000"))
        self.label_voluntary_pension.setText(_translate("payrolDialog", "1,820"))
        self.label_loan.setText(_translate("payrolDialog", "48,500"))
        self.label_total_deductions.setText(_translate("payrolDialog", "82,325"))
        self.label_12.setText(_translate("payrolDialog", "Total Deductions:"))
        self.label_pfnum.setText(_translate("payrolDialog", "None"))
        self.label_31.setText(_translate("payrolDialog", "Name:"))
        self.label_32.setText(_translate("payrolDialog", "KRA Pin:"))
        self.label_kra_pin.setText(_translate("payrolDialog", "A00000005000L"))
        self.label_34.setText(_translate("payrolDialog", "Age:"))
        self.label_bank_name.setText(_translate("payrolDialog", "None"))
        self.label_net_pay.setText(_translate("payrolDialog", "112,065"))
        self.pushButton.setText(_translate("payrolDialog", "Pay"))
        self.groupBox.setTitle(_translate("payrolDialog", "Allowances"))
        self.checkBox_bsalary.setText(_translate("payrolDialog", "Basic Salary"))
        self.checkBox_hse_allowance.setText(_translate("payrolDialog", "Rental House Allowance"))
        self.checkBox_med_allowance.setText(_translate("payrolDialog", "Medical Allowance"))
        self.checkBox_oth_allowance.setText(_translate("payrolDialog", "Any other Allowances"))
        self.label_bsalary.setText(_translate("payrolDialog", "145,000"))
        self.label_hse_allowance.setText(_translate("payrolDialog", "21,000"))
        self.label_med_allowance.setText(_translate("payrolDialog", "15,890"))
        self.label_oth_allowance.setText(_translate("payrolDialog", "12,500"))
        self.label_28.setText(_translate("payrolDialog", "Gross Salary:"))
        self.label_gross_salary.setText(_translate("payrolDialog", "194,390"))
        self.checkBox.setText(_translate("payrolDialog", "Sick Pay"))
        self.label.setText(_translate("payrolDialog", "12297"))
        self.pushButton_2.setText(_translate("payrolDialog", "Cancel"))
        self.groupBox_3.setTitle(_translate("payrolDialog", "Income type"))
        self.radioButton.setText(_translate("payrolDialog", "Salary"))
        self.radioButton_2.setText(_translate("payrolDialog", "Wages"))
        self.radioButton_3.setText(_translate("payrolDialog", "Commision"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    payrolDialog = QtWidgets.QDialog()
    ui = Ui_payrolDialog()
    ui.setupUi(payrolDialog)
    payrolDialog.show()
    sys.exit(app.exec_())

