# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'receipt.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReceiptDialog(object):
    def setupUi(self, ReceiptDialog):
        ReceiptDialog.setObjectName("ReceiptDialog")
        ReceiptDialog.resize(1245, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/dollar-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReceiptDialog.setWindowIcon(icon)
        ReceiptDialog.setStyleSheet("background-color:rgb(170, 255, 255)")
        self.label_12 = QtWidgets.QLabel(ReceiptDialog)
        self.label_12.setGeometry(QtCore.QRect(70, 50, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(24)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(ReceiptDialog)
        self.line_2.setGeometry(QtCore.QRect(10, 100, 1211, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(ReceiptDialog)
        self.label.setGeometry(QtCore.QRect(270, 9, 600, 41))
        self.label.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(28)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet(")")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(ReceiptDialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 1201, 441))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listView_pay_for = QtWidgets.QListWidget(self.tab)
        self.listView_pay_for.setGeometry(QtCore.QRect(10, 70, 321, 241))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.listView_pay_for.setFont(font)
        self.listView_pay_for.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.listView_pay_for.setFrameShape(QtWidgets.QFrame.Panel)
        self.listView_pay_for.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listView_pay_for.setLineWidth(3)
        self.listView_pay_for.setMidLineWidth(1)
        self.listView_pay_for.setAutoScrollMargin(16)
        self.listView_pay_for.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_pay_for.setProperty("showDropIndicator", False)
        self.listView_pay_for.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listView_pay_for.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.listView_pay_for.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listView_pay_for.setMovement(QtWidgets.QListView.Snap)
        self.listView_pay_for.setFlow(QtWidgets.QListView.TopToBottom)
        self.listView_pay_for.setProperty("isWrapping", False)
        self.listView_pay_for.setResizeMode(QtWidgets.QListView.Adjust)
        self.listView_pay_for.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listView_pay_for.setViewMode(QtWidgets.QListView.ListMode)
        self.listView_pay_for.setUniformItemSizes(True)
        self.listView_pay_for.setBatchSize(150)
        self.listView_pay_for.setWordWrap(True)
        self.listView_pay_for.setObjectName("listView_pay_for")
        self.lineEdit_search = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_search.setGeometry(QtCore.QRect(500, 10, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_search.setFont(font)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.pushButton_add = QtWidgets.QPushButton(self.tab)
        self.pushButton_add.setGeometry(QtCore.QRect(80, 340, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/icons/coin-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon1)
        self.pushButton_add.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_add.setObjectName("pushButton_add")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(340, 50, 851, 261))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Kenya))
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_banking = QtWidgets.QWidget()
        self.tab_banking.setObjectName("tab_banking")
        self.label_15 = QtWidgets.QLabel(self.tab_banking)
        self.label_15.setGeometry(QtCore.QRect(510, 90, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.line_4 = QtWidgets.QFrame(self.tab_banking)
        self.line_4.setGeometry(QtCore.QRect(20, 250, 1121, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_16 = QtWidgets.QLabel(self.tab_banking)
        self.label_16.setGeometry(QtCore.QRect(510, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_amout_payable = QtWidgets.QLabel(self.tab_banking)
        self.label_amout_payable.setGeometry(QtCore.QRect(690, 90, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_amout_payable.setFont(font)
        self.label_amout_payable.setObjectName("label_amout_payable")
        self.label_5 = QtWidgets.QLabel(self.tab_banking)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 101, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_amount_due = QtWidgets.QLabel(self.tab_banking)
        self.label_amount_due.setGeometry(QtCore.QRect(690, 120, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_amount_due.setFont(font)
        self.label_amount_due.setObjectName("label_amount_due")
        self.label_penalties = QtWidgets.QLabel(self.tab_banking)
        self.label_penalties.setGeometry(QtCore.QRect(690, 150, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_penalties.setFont(font)
        self.label_penalties.setObjectName("label_penalties")
        self.lineEdit_transaction_code = QtWidgets.QLineEdit(self.tab_banking)
        self.lineEdit_transaction_code.setGeometry(QtCore.QRect(190, 60, 251, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_transaction_code.setFont(font)
        self.lineEdit_transaction_code.setObjectName("lineEdit_transaction_code")
        self.label_17 = QtWidgets.QLabel(self.tab_banking)
        self.label_17.setGeometry(QtCore.QRect(510, 150, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.dateEdit_transaction_date = QtWidgets.QDateEdit(self.tab_banking)
        self.dateEdit_transaction_date.setGeometry(QtCore.QRect(190, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_transaction_date.setFont(font)
        self.dateEdit_transaction_date.setCalendarPopup(True)
        self.dateEdit_transaction_date.setDate(QtCore.QDate(2019, 1, 1))
        self.dateEdit_transaction_date.setObjectName("dateEdit_transaction_date")
        self.lineEdit_amount_banked = QtWidgets.QLineEdit(self.tab_banking)
        self.lineEdit_amount_banked.setGeometry(QtCore.QRect(190, 150, 251, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_amount_banked.setFont(font)
        self.lineEdit_amount_banked.setObjectName("lineEdit_amount_banked")
        self.label_3 = QtWidgets.QLabel(self.tab_banking)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 131, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_banking)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_18 = QtWidgets.QLabel(self.tab_banking)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.comboBox_bank_name = QtWidgets.QComboBox(self.tab_banking)
        self.comboBox_bank_name.setGeometry(QtCore.QRect(190, 20, 291, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_bank_name.setFont(font)
        self.comboBox_bank_name.setObjectName("comboBox_bank_name")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.comboBox_bank_name.addItem("")
        self.label_19 = QtWidgets.QLabel(self.tab_banking)
        self.label_19.setGeometry(QtCore.QRect(510, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_tcode = QtWidgets.QLabel(self.tab_banking)
        self.label_tcode.setGeometry(QtCore.QRect(590, 20, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_tcode.setFont(font)
        self.label_tcode.setText("")
        self.label_tcode.setObjectName("label_tcode")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/icons/office-block.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_banking, icon2, "")
        self.tab_cash = QtWidgets.QWidget()
        self.tab_cash.setObjectName("tab_cash")
        self.label_20 = QtWidgets.QLabel(self.tab_cash)
        self.label_20.setGeometry(QtCore.QRect(20, 20, 111, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_cash)
        self.label_21.setGeometry(QtCore.QRect(20, 70, 171, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_cash)
        self.label_22.setGeometry(QtCore.QRect(20, 120, 111, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_cash)
        self.label_23.setGeometry(QtCore.QRect(450, 70, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_cash)
        self.label_24.setGeometry(QtCore.QRect(450, 100, 101, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_cash)
        self.label_25.setGeometry(QtCore.QRect(450, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit_amount_paid = QtWidgets.QLineEdit(self.tab_cash)
        self.lineEdit_amount_paid.setGeometry(QtCore.QRect(200, 20, 171, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_amount_paid.setFont(font)
        self.lineEdit_amount_paid.setObjectName("lineEdit_amount_paid")
        self.lineEdit_user_transaction_code = QtWidgets.QLineEdit(self.tab_cash)
        self.lineEdit_user_transaction_code.setGeometry(QtCore.QRect(200, 70, 171, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_user_transaction_code.setFont(font)
        self.lineEdit_user_transaction_code.setObjectName("lineEdit_user_transaction_code")
        self.lineEdit__cashier = QtWidgets.QLineEdit(self.tab_cash)
        self.lineEdit__cashier.setGeometry(QtCore.QRect(200, 120, 171, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit__cashier.setFont(font)
        self.lineEdit__cashier.setObjectName("lineEdit__cashier")
        self.label_26 = QtWidgets.QLabel(self.tab_cash)
        self.label_26.setGeometry(QtCore.QRect(450, 160, 91, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_amount_payable = QtWidgets.QLabel(self.tab_cash)
        self.label_amount_payable.setGeometry(QtCore.QRect(670, 70, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_amount_payable.setFont(font)
        self.label_amount_payable.setObjectName("label_amount_payable")
        self.label_amount_due_cash = QtWidgets.QLabel(self.tab_cash)
        self.label_amount_due_cash.setGeometry(QtCore.QRect(670, 100, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_amount_due_cash.setFont(font)
        self.label_amount_due_cash.setObjectName("label_amount_due_cash")
        self.label_penalties_2 = QtWidgets.QLabel(self.tab_cash)
        self.label_penalties_2.setGeometry(QtCore.QRect(670, 130, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_penalties_2.setFont(font)
        self.label_penalties_2.setObjectName("label_penalties_2")
        self.label_change_due = QtWidgets.QLabel(self.tab_cash)
        self.label_change_due.setGeometry(QtCore.QRect(670, 160, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_change_due.setFont(font)
        self.label_change_due.setObjectName("label_change_due")
        self.label_27 = QtWidgets.QLabel(self.tab_cash)
        self.label_27.setGeometry(QtCore.QRect(450, 20, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_tcode_2 = QtWidgets.QLabel(self.tab_cash)
        self.label_tcode_2.setGeometry(QtCore.QRect(590, 20, 221, 20))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_tcode_2.setFont(font)
        self.label_tcode_2.setText("")
        self.label_tcode_2.setObjectName("label_tcode_2")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/money.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_cash, icon3, "")
        self.tab_mpesa = QtWidgets.QWidget()
        self.tab_mpesa.setObjectName("tab_mpesa")
        self.label_28 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_28.setGeometry(QtCore.QRect(20, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_29.setGeometry(QtCore.QRect(20, 70, 191, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_30.setGeometry(QtCore.QRect(20, 120, 181, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_31.setGeometry(QtCore.QRect(20, 170, 101, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_32.setGeometry(QtCore.QRect(500, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_33.setGeometry(QtCore.QRect(690, 110, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_34.setGeometry(QtCore.QRect(690, 170, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_35.setGeometry(QtCore.QRect(690, 80, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_36.setGeometry(QtCore.QRect(500, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_37.setGeometry(QtCore.QRect(500, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_38.setGeometry(QtCore.QRect(500, 170, 91, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_39.setGeometry(QtCore.QRect(690, 140, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_mpesa)
        self.lineEdit_7.setGeometry(QtCore.QRect(230, 20, 251, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_mpesa)
        self.lineEdit_8.setGeometry(QtCore.QRect(230, 70, 161, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_mpesa)
        self.lineEdit_9.setGeometry(QtCore.QRect(230, 120, 161, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_mpesa)
        self.lineEdit_10.setGeometry(QtCore.QRect(230, 170, 161, 20))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab_mpesa)
        self.dateEdit_2.setGeometry(QtCore.QRect(660, 20, 171, 22))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setDate(QtCore.QDate(2019, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_40 = QtWidgets.QLabel(self.tab_mpesa)
        self.label_40.setGeometry(QtCore.QRect(500, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../images/icons/smartphone-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_mpesa, icon4, "")
        self.pushButton_cancel = QtWidgets.QPushButton(self.tab)
        self.pushButton_cancel.setGeometry(QtCore.QRect(260, 340, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../images/icons/web-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cancel.setIcon(icon5)
        self.pushButton_cancel.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.pushButton_search = QtWidgets.QPushButton(self.tab)
        self.pushButton_search.setGeometry(QtCore.QRect(1020, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../images/icons8-search-50 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search.setIcon(icon6)
        self.pushButton_search.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_search.setObjectName("pushButton_search")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.toolButton_search = QtWidgets.QToolButton(self.tab)
        self.toolButton_search.setGeometry(QtCore.QRect(1120, 10, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolButton_search.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../images/data-visualization.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_search.setIcon(icon7)
        self.toolButton_search.setIconSize(QtCore.QSize(30, 30))
        self.toolButton_search.setCheckable(False)
        self.toolButton_search.setObjectName("toolButton_search")
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(10, 50, 131, 16))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableView_payment_results = QtWidgets.QTableView(self.tab_2)
        self.tableView_payment_results.setGeometry(QtCore.QRect(10, 10, 1171, 331))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableView_payment_results.setFont(font)
        self.tableView_payment_results.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.tableView_payment_results.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableView_payment_results.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableView_payment_results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_payment_results.setAlternatingRowColors(True)
        self.tableView_payment_results.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_payment_results.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_payment_results.setObjectName("tableView_payment_results")
        self.tableView_payment_results.horizontalHeader().setDefaultSectionSize(200)
        self.pushButton_amend = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_amend.setGeometry(QtCore.QRect(20, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_amend.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../images/dollar-symbol-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_amend.setIcon(icon8)
        self.pushButton_amend.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_amend.setObjectName("pushButton_amend")
        self.pushButton_print = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_print.setGeometry(QtCore.QRect(170, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_print.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../images/icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_print.setIcon(icon9)
        self.pushButton_print.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_print.setObjectName("pushButton_print")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(ReceiptDialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ReceiptDialog)

    def retranslateUi(self, ReceiptDialog):
        _translate = QtCore.QCoreApplication.translate
        ReceiptDialog.setWindowTitle(_translate("ReceiptDialog", "Payments"))
        self.label_12.setText(_translate("ReceiptDialog", "Receipt  Processing"))
        self.label.setText(_translate("ReceiptDialog", "Human Resourse Management System"))
        self.listView_pay_for.setSortingEnabled(False)
        self.lineEdit_search.setPlaceholderText(_translate("ReceiptDialog", "Enter Payment Reference Number then click search"))
        self.pushButton_add.setText(_translate("ReceiptDialog", "Add Payments"))
        self.label_15.setText(_translate("ReceiptDialog", "Amount Payable :"))
        self.label_16.setText(_translate("ReceiptDialog", "Due Amount :"))
        self.label_amout_payable.setText(_translate("ReceiptDialog", "0.00"))
        self.label_5.setText(_translate("ReceiptDialog", "Transaction No. :"))
        self.label_amount_due.setText(_translate("ReceiptDialog", "0.00"))
        self.label_penalties.setText(_translate("ReceiptDialog", "0.00"))
        self.label_17.setText(_translate("ReceiptDialog", "Penalties :"))
        self.label_3.setText(_translate("ReceiptDialog", "Transaction Date :"))
        self.label_4.setText(_translate("ReceiptDialog", "Banked Amount :"))
        self.label_18.setText(_translate("ReceiptDialog", "Bank Name"))
        self.comboBox_bank_name.setItemText(0, _translate("ReceiptDialog", "Please Select.."))
        self.comboBox_bank_name.setItemText(1, _translate("ReceiptDialog", "National Bank"))
        self.comboBox_bank_name.setItemText(2, _translate("ReceiptDialog", "KCB"))
        self.comboBox_bank_name.setItemText(3, _translate("ReceiptDialog", "Transnational Bank"))
        self.comboBox_bank_name.setItemText(4, _translate("ReceiptDialog", "Barclays"))
        self.comboBox_bank_name.setItemText(5, _translate("ReceiptDialog", "Co-operative Bank"))
        self.comboBox_bank_name.setItemText(6, _translate("ReceiptDialog", "Standard Chattered Bank"))
        self.comboBox_bank_name.setItemText(7, _translate("ReceiptDialog", "Equity Bank"))
        self.comboBox_bank_name.setItemText(8, _translate("ReceiptDialog", "Family Bank"))
        self.comboBox_bank_name.setItemText(9, _translate("ReceiptDialog", "Diamond Trust Bank"))
        self.comboBox_bank_name.setItemText(10, _translate("ReceiptDialog", "abc Bank"))
        self.comboBox_bank_name.setItemText(11, _translate("ReceiptDialog", "Chase Bank"))
        self.comboBox_bank_name.setItemText(12, _translate("ReceiptDialog", "Eco Bank"))
        self.comboBox_bank_name.setItemText(13, _translate("ReceiptDialog", "I&M Bank"))
        self.comboBox_bank_name.setItemText(14, _translate("ReceiptDialog", "K-Rep Bank"))
        self.comboBox_bank_name.setItemText(15, _translate("ReceiptDialog", "NIC Bank"))
        self.comboBox_bank_name.setItemText(16, _translate("ReceiptDialog", "Post Bank"))
        self.label_19.setText(_translate("ReceiptDialog", "Code:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_banking), _translate("ReceiptDialog", "Banking"))
        self.label_20.setText(_translate("ReceiptDialog", "Amount Paid :"))
        self.label_21.setText(_translate("ReceiptDialog", "User Transaction  Code :"))
        self.label_22.setText(_translate("ReceiptDialog", "Cashier Name :"))
        self.label_23.setText(_translate("ReceiptDialog", "Amount Payable :"))
        self.label_24.setText(_translate("ReceiptDialog", "Amount Due :"))
        self.label_25.setText(_translate("ReceiptDialog", "Penanties :"))
        self.label_26.setText(_translate("ReceiptDialog", "Change Due :"))
        self.label_amount_payable.setText(_translate("ReceiptDialog", "0.00"))
        self.label_amount_due_cash.setText(_translate("ReceiptDialog", "0.00"))
        self.label_penalties_2.setText(_translate("ReceiptDialog", "0.00"))
        self.label_change_due.setText(_translate("ReceiptDialog", "0.00"))
        self.label_27.setText(_translate("ReceiptDialog", "Timestamp :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_cash), _translate("ReceiptDialog", "Cash"))
        self.label_28.setText(_translate("ReceiptDialog", "Payer Name :"))
        self.label_29.setText(_translate("ReceiptDialog", "Transaction Phone Number :"))
        self.label_30.setText(_translate("ReceiptDialog", "Transaction Mpesa Code :"))
        self.label_31.setText(_translate("ReceiptDialog", "Paid amount :"))
        self.label_32.setText(_translate("ReceiptDialog", "Amount Payable :"))
        self.label_33.setText(_translate("ReceiptDialog", "0.00"))
        self.label_34.setText(_translate("ReceiptDialog", "0.00"))
        self.label_35.setText(_translate("ReceiptDialog", "0.00"))
        self.label_36.setText(_translate("ReceiptDialog", "Amount Due :"))
        self.label_37.setText(_translate("ReceiptDialog", "Penanties :"))
        self.label_38.setText(_translate("ReceiptDialog", "Change Due :"))
        self.label_39.setText(_translate("ReceiptDialog", "0.00"))
        self.label_40.setText(_translate("ReceiptDialog", "Transaction Date :"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_mpesa), _translate("ReceiptDialog", "M-Pesa"))
        self.pushButton_cancel.setText(_translate("ReceiptDialog", "Cancel"))
        self.pushButton_search.setText(_translate("ReceiptDialog", "Search"))
        self.label_2.setText(_translate("ReceiptDialog", "Payment Reference No. :"))
        self.toolButton_search.setToolTip(_translate("ReceiptDialog", "Advance Search"))
        self.toolButton_search.setStatusTip(_translate("ReceiptDialog", "Use"))
        self.toolButton_search.setText(_translate("ReceiptDialog", "..."))
        self.label_41.setText(_translate("ReceiptDialog", "PAYMENTS FOR :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ReceiptDialog", "Make Payments"))
        self.pushButton_amend.setText(_translate("ReceiptDialog", "Amend"))
        self.pushButton_print.setText(_translate("ReceiptDialog", "Print"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ReceiptDialog", "View Payments"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiptDialog = QtWidgets.QDialog()
    ui = Ui_ReceiptDialog()
    ui.setupUi(ReceiptDialog)
    ReceiptDialog.show()
    sys.exit(app.exec_())

